export interface GuideModuleTab {
  key: string;
  label: string;
  purpose: string;
  inputFields: string[];
  buttons: string[];
  autoPulled: string[];
  outputs: string[];
  commonErrors: string[];
}

export interface GuideModule {
  key: string;
  label: string;
  routePath: string;
  phase: string;
  purpose: string;
  prerequisites: string[];
  isaReferences: string[];
  roles: string[];
  approvals: string[];
  locks: string[];
  tabs: GuideModuleTab[];
  workedExample: string;
}

export const USER_GUIDE_REGISTRY: GuideModule[] = [
  // ═══════════════════════════════════════════════════════════════
  // Phase 1: Firm Administration (1.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "administration",
    label: "Firm Settings",
    routePath: "/administration",
    phase: "Firm Administration",
    purpose: "Centralized control for RBAC settings, maker-checker configuration, engagement flags, and document templates.",
    prerequisites: ["Admin or Partner role"],
    isaReferences: ["ISQM 1"],
    roles: ["Admin", "Partner"],
    approvals: ["Partner approval for firm-wide configuration changes"],
    locks: ["Settings locked during active audit season by Partner override"],
    tabs: [],
    workedExample: "Admin configures maker-checker for TB uploads, sets 3-level approval for materiality, enables AI features firm-wide.",
  },
  {
    key: "users",
    label: "Users & Roles",
    routePath: "/users",
    phase: "Firm Administration",
    purpose: "Manage user accounts, role assignments, and access permissions across the firm.",
    prerequisites: ["Firm Settings configured", "Admin role"],
    isaReferences: ["ISQM 1"],
    roles: ["Admin"],
    approvals: ["Admin approval for role changes"],
    locks: ["User roles locked during active engagement assignments"],
    tabs: [],
    workedExample: "Admin creates 8 user accounts: 1 Partner, 1 Manager, 2 Seniors, 3 Staff, 1 EQCR Reviewer.",
  },
  {
    key: "firm-wide-controls",
    label: "Firm-Wide Controls",
    routePath: "/firm-controls",
    phase: "Firm Administration",
    purpose: "Manage firm-level quality controls, policies, and ISQM 1 compliance requirements. Covers leadership responsibilities, ethical requirements, human resources, engagement performance, and monitoring.",
    prerequisites: ["Firm Settings configured", "Users & Roles set up", "Admin or Partner role"],
    isaReferences: ["ISQM 1", "ISA 220"],
    roles: ["Admin", "Partner"],
    approvals: ["Partner approval for policy changes"],
    locks: ["Controls locked during active inspection period"],
    tabs: [
      { key: "quality-objectives", label: "Quality Objectives", purpose: "Define and monitor firm-wide quality objectives per ISQM 1 components", inputFields: ["Objective description", "Target metric", "Owner", "Status"], buttons: ["Add Objective", "Update Status", "Generate Report"], autoPulled: ["Prior year objectives"], outputs: ["Quality objectives register", "Compliance dashboard"], commonErrors: ["Missing quality objectives for required ISQM 1 components"] },
      { key: "policies", label: "Policies & Procedures", purpose: "Maintain firm audit policies, methodology, and standard procedures", inputFields: ["Policy title", "Effective date", "Review date", "Policy content"], buttons: ["Add Policy", "Version Update", "Distribute"], autoPulled: [], outputs: ["Policy register", "Distribution log"], commonErrors: ["Expired policies not updated"] },
      { key: "monitoring", label: "Monitoring & Remediation", purpose: "Track identified deficiencies, root cause analysis, and remediation actions", inputFields: ["Deficiency description", "Root cause", "Remediation plan", "Due date"], buttons: ["Log Deficiency", "Assign Remediation", "Mark Resolved"], autoPulled: ["Inspection findings", "EQCR feedback"], outputs: ["Deficiency tracker", "Remediation status report"], commonErrors: ["Overdue remediation actions"] },
    ],
    workedExample: "Firm defines 8 quality objectives aligned to ISQM 1 components. 2 deficiencies identified from prior inspection: staff training gap and documentation standards. Remediation plans assigned with Q1 2025 target.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 2: Client & Engagement (2.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "clients",
    label: "Clients Management",
    routePath: "/clients",
    phase: "Client & Engagement",
    purpose: "Manage client master records including company details, SECP registration, NTN, industry classification.",
    prerequisites: ["Firm Administration completed", "Logged-in user with Manager or above role"],
    isaReferences: ["ISQM 1", "ISA 220"],
    roles: ["Manager", "Partner", "Admin"],
    approvals: ["Manager approval for new client creation"],
    locks: ["Client record locked after engagement creation"],
    tabs: [],
    workedExample: "ABC & Co. (Private) Limited is registered with SECP No. 0012345, NTN 1234567-8, Manufacturing industry.",
  },
  {
    key: "client-onboarding",
    label: "Client Onboarding",
    routePath: "/onboarding/:id",
    phase: "Client & Engagement",
    purpose: "Guided onboarding wizard for new audit clients. Captures entity details, industry classification, regulatory registrations, key contacts, and initial risk profile to create a complete client record.",
    prerequisites: ["Client record created in Clients Management", "Manager or above role"],
    isaReferences: ["ISQM 1", "ISA 220", "ISA 315"],
    roles: ["Manager", "Partner", "Admin"],
    approvals: ["Partner approval for high-risk clients"],
    locks: ["Client profile locked after onboarding completion"],
    tabs: [
      { key: "entity-details", label: "Entity Details", purpose: "Capture company registration, NTN, SECP details, and legal structure", inputFields: ["Company name", "Registration number", "NTN", "Legal structure", "Date of incorporation"], buttons: ["Save", "Validate NTN"], autoPulled: [], outputs: ["Client master record"], commonErrors: ["Missing registration number", "Invalid NTN format"] },
      { key: "industry-profile", label: "Industry & Profile", purpose: "Classify client by industry, size, and regulatory requirements", inputFields: ["Industry classification", "Revenue bracket", "Employee count", "Listed/Unlisted"], buttons: ["Auto-Classify", "Save"], autoPulled: [], outputs: ["Industry risk profile"], commonErrors: ["Incorrect industry classification"] },
      { key: "contacts", label: "Key Contacts", purpose: "Record key client personnel and their roles for engagement communication", inputFields: ["Contact name", "Designation", "Email", "Phone", "Role in audit"], buttons: ["Add Contact", "Set Primary Contact"], autoPulled: [], outputs: ["Contact directory"], commonErrors: ["Missing primary contact"] },
      { key: "risk-screening", label: "Initial Risk Screening", purpose: "Preliminary risk assessment for client acceptance decision", inputFields: ["Risk questionnaire responses", "AML screening results"], buttons: ["Run Screening", "Generate Risk Score"], autoPulled: ["Industry risk benchmarks"], outputs: ["Risk screening report", "Risk score"], commonErrors: ["Incomplete screening questionnaire"] },
    ],
    workedExample: "For ABC & Co. (Private) Limited, onboarding captures SECP No. 0012345, NTN 1234567-8, Manufacturing industry. 3 key contacts added. Initial risk score: Medium. Partner approves onboarding.",
  },
  {
    key: "engagements",
    label: "Engagements List",
    routePath: "/engagements",
    phase: "Client & Engagement",
    purpose: "Lists all audit engagements with filtering, search, status indicators, and quick access to workspace.",
    prerequisites: ["Client record created and onboarded", "Logged-in user"],
    isaReferences: ["ISQM 1"],
    roles: ["All roles (filtered by access)"],
    approvals: ["Partner approval for new engagement creation"],
    locks: ["Engagement locked after final sign-off in Finalization"],
    tabs: [],
    workedExample: "ABC & Co. (Private) Limited - ABC-SA-2025-001 appears as Active with FY2025 period.",
  },
  {
    key: "engagement-allocation",
    label: "Engagement Allocation",
    routePath: "/allocation",
    phase: "Client & Engagement",
    purpose: "Assign team members to engagements with role-based allocation. View team workload, availability, and assignment history. Supports drag-and-drop allocation and bulk assignment for efficient resource management.",
    prerequisites: ["Users & Roles configured", "Engagements created", "Manager or above role"],
    isaReferences: ["ISA 220", "ISQM 1"],
    roles: ["Manager", "Partner", "Admin"],
    approvals: ["Partner approval for senior team changes"],
    locks: ["Allocation locked during active fieldwork"],
    tabs: [],
    workedExample: "Manager allocates 2 Seniors and 3 Staff to ABC & Co. FY2025 engagement. Partner reviews workload dashboard and approves allocation.",
  },
  {
    key: "pdf-documentation",
    label: "PDF Documentation",
    routePath: "/pdf-documentation",
    phase: "Client & Engagement",
    purpose: "Firm-wide document management system for generating, storing, and distributing PDF documentation including engagement letters, representation letters, management letters, and audit reports. Supports template-based generation with firm branding.",
    prerequisites: ["Admin or Partner role", "Firm Settings configured"],
    isaReferences: ["ISA 230", "ISA 580", "ISA 700"],
    roles: ["Admin", "Partner"],
    approvals: ["Partner approval for external document distribution"],
    locks: ["Documents locked after final issuance"],
    tabs: [],
    workedExample: "Admin generates engagement letter template for FY2025 cycle. Partner reviews and approves for distribution to 5 audit clients.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 3: Pre-Planning (3.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "pre-planning",
    label: "Pre-Planning",
    routePath: "/workspace/:id/pre-planning",
    phase: "Pre-Planning",
    purpose: "Enforces completion of all pre-engagement requirements before audit fieldwork begins. Covers client acceptance, independence, ethics, engagement letter, and team allocation.",
    prerequisites: ["Engagement created in Engagements List", "Client data loaded from Client & Engagement phase"],
    isaReferences: ["ISA 210", "ISA 220", "ISQM 1", "ISA 300"],
    roles: ["Staff", "Senior", "Manager", "Partner"],
    approvals: ["Partner sign-off required for phase completion"],
    locks: ["Phase locked after Partner approval"],
    tabs: [
      { key: "setup", label: "Engagement Setup (ISA 300/210)", purpose: "Configure engagement parameters, fiscal year, reporting framework, and currency", inputFields: ["Client Name", "Engagement Code", "Fiscal Year", "Reporting Framework", "Currency"], buttons: ["Save"], autoPulled: ["Client master data"], outputs: ["Engagement configuration"], commonErrors: ["Missing required fields"] },
      { key: "entity-understanding", label: "Entity Understanding (ISA 315)", purpose: "Document understanding of the entity's nature, environment, and internal controls", inputFields: ["Entity background", "Industry environment", "Business operations", "Governance structure"], buttons: ["Generate AI Content"], autoPulled: ["Client history"], outputs: ["Entity understanding documentation"], commonErrors: ["Incomplete entity description"] },
      { key: "ethics", label: "Ethics & Independence (ISA 220)", purpose: "Ethical compliance checks, independence declarations, and conflict of interest assessment", inputFields: ["Independence declarations", "Ethics checklist responses"], buttons: ["Complete Ethics Review", "Confirm Independence"], autoPulled: ["Team roster"], outputs: ["Ethics compliance record", "Independence confirmations"], commonErrors: ["Missing team member declarations"] },
      { key: "acceptance", label: "Acceptance & Continuance (ISA 210/220)", purpose: "Assess whether to accept or continue the client relationship with due diligence", inputFields: ["Risk assessment responses", "Due diligence questionnaire", "AML/KYC checks"], buttons: ["Generate AI Assessment", "Approve", "Reject"], autoPulled: ["Client history", "Prior year findings"], outputs: ["Acceptance decision", "Risk rating"], commonErrors: ["Incomplete due diligence"] },
      { key: "engagement-letter", label: "Engagement Letter (ISA 210)", purpose: "Draft and manage the engagement letter with terms and scope", inputFields: ["Engagement terms", "Scope", "Fees", "Timeline"], buttons: ["Generate Letter", "Send for Signing", "Upload Signed Copy"], autoPulled: ["Client details", "Engagement type"], outputs: ["Signed engagement letter"], commonErrors: ["Missing client signature"] },
      { key: "signoff", label: "Completion & Sign-off (ISA 300)", purpose: "Final partner review and approval gate for pre-planning phase", inputFields: ["Review comments"], buttons: ["Approve", "Request Changes"], autoPulled: ["All pre-planning section statuses"], outputs: ["Phase gate approval"], commonErrors: ["Incomplete sections blocking approval"] },
    ],
    workedExample: "For ABC & Co., Partner reviews all 6 sections. Entity understanding documented. Independence confirmed for 4 team members. Engagement letter signed. Partner approves pre-planning gate.",
  },
  {
    key: "ethics-independence",
    label: "Ethics & Independence",
    routePath: "/workspace/:id/ethics",
    phase: "Pre-Planning",
    purpose: "Independence and ethics compliance checklist per ISA 220 and IESBA Code. Tracks team independence confirmations, client acceptance/continuance evaluation, AML/CFT assessment, engagement letter status, fee arrangements, related parties, and conflicts of interest.",
    prerequisites: ["Engagement created", "Team members allocated"],
    isaReferences: ["ISA 220", "ISQM 1", "IESBA Code"],
    roles: ["Staff", "Senior", "Manager", "Partner"],
    approvals: ["Partner sign-off on independence"],
    locks: ["Checklist locked after Partner approval"],
    tabs: [],
    workedExample: "For ABC & Co., all 7 checklist items completed: independence confirmations received from 4 team members, client continuance evaluation completed, AML screening passed, engagement letter signed. Partner approves ethics and independence.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 4: Information Gathering (4.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "requisition",
    label: "Data Intake",
    routePath: "/workspace/:id/requisition",
    phase: "Information Gathering",
    purpose: "Central data intake hub using the unified AuditWise Excel template for GL, TB, AP, AR, Bank, and Confirmations upload. Manages data ingestion via a single-file upload flow with validation, sync-to-core, reconciliation tracking, Chart of Accounts review, FS Mapping, and Draft FS generation.",
    prerequisites: ["Pre-Planning completed and approved", "Engagement created", "Client assigned", "Team allocated"],
    isaReferences: ["ISA 230", "ISA 315", "ISA 500"],
    roles: ["Staff", "Senior", "Manager", "Partner"],
    approvals: ["Upload approval (Maker-Checker)", "CoA mapping approval"],
    locks: ["Data locked after TB reconciliation approved", "FS Mapping locked after Approve & Lock"],
    tabs: [
      { key: "upload", label: "Upload", purpose: "Unified Excel upload using the AuditWise template containing TB, GL, AP, AR, Bank, and Confirmations sheets", inputFields: ["AuditWise Excel template file", "Reporting period", "Currency"], buttons: ["Upload File", "Download Template", "Validate", "Approve Upload"], autoPulled: ["Currency from engagement", "Period from engagement"], outputs: ["Parsed data batches (TB, GL, AP, AR, Bank, Confirmations)", "Validation report"], commonErrors: ["Invalid file format", "Missing required sheets", "TB does not balance", "Duplicate GL codes"] },
      { key: "summary", label: "Summary", purpose: "Data overview with sync-to-core status, reconciliation indicators, and data quality metrics", inputFields: [], buttons: ["Sync to Core", "Refresh", "Export Summary"], autoPulled: ["GL totals", "TB totals", "CoA mapping stats", "Reconciliation status"], outputs: ["Data quality dashboard", "Sync status report"], commonErrors: ["Sync failed due to unmapped accounts", "TB/GL mismatch"] },
      { key: "review-coa", label: "Review & CoA", purpose: "Chart of Accounts review with sub-tabs for each data type, FS Mapping, and Draft FS preview", inputFields: ["CoA adjustments", "FS line item assignments"], buttons: ["Auto-Classify", "Apply Template", "Map to FS"], autoPulled: ["Industry from client profile", "Uploaded data from all sheets"], outputs: ["Classified CoA", "FS Mapping records", "Draft Financial Statements"], commonErrors: ["Duplicate account codes", "Missing FS line item mapping", "Unmapped GL codes"] },
      { key: "review-tb", label: "TB", purpose: "Review uploaded Trial Balance data with debit/credit totals and variance analysis", inputFields: ["TB line item edits", "Adjustments"], buttons: ["Refresh", "Export TB"], autoPulled: ["TB data from upload"], outputs: ["Validated TB summary"], commonErrors: ["TB imbalance", "Missing account codes"] },
      { key: "review-gl", label: "GL", purpose: "Review General Ledger detail with filtering, grouping, and reconciliation to TB", inputFields: ["GL filters", "Date range"], buttons: ["Reconcile to TB", "Export GL"], autoPulled: ["GL data from upload"], outputs: ["GL detail report", "TB-GL reconciliation"], commonErrors: ["GL total does not match TB", "Missing journal entries"] },
      { key: "review-ap", label: "AP", purpose: "Review Accounts Payable sub-ledger data", inputFields: ["AP vendor filters"], buttons: ["Reconcile to TB", "Export AP"], autoPulled: ["AP data from upload"], outputs: ["AP aging report"], commonErrors: ["AP total does not match TB payable balance"] },
      { key: "review-ar", label: "AR", purpose: "Review Accounts Receivable sub-ledger data", inputFields: ["AR customer filters"], buttons: ["Reconcile to TB", "Export AR"], autoPulled: ["AR data from upload"], outputs: ["AR aging report"], commonErrors: ["AR total does not match TB receivable balance"] },
      { key: "review-bank", label: "Bank", purpose: "Review bank statement data for reconciliation", inputFields: ["Bank account filters"], buttons: ["Bank Reconciliation", "Export"], autoPulled: ["Bank data from upload"], outputs: ["Bank reconciliation report"], commonErrors: ["Unreconciled items"] },
      { key: "review-confirmations", label: "Confirmations", purpose: "Manage third-party confirmations per ISA 505", inputFields: ["Confirmation type", "Counterparty details"], buttons: ["Generate Confirmation", "Track Response"], autoPulled: ["Confirmation data from upload"], outputs: ["Confirmation log", "Response tracker"], commonErrors: ["Missing confirmation responses"] },
      { key: "review-fs-mapping", label: "FS Mapping", purpose: "Map Chart of Accounts to FS line items using AI auto-map with confidence scores", inputFields: ["FS line item assignments", "Override selections"], buttons: ["Auto-Map", "Approve Mapping", "Lock"], autoPulled: ["CoA records", "FS Head templates"], outputs: ["FS Mapping records", "Reconciliation ribbon"], commonErrors: ["Low-confidence mappings not reviewed", "TB total vs mapped total mismatch"] },
      { key: "review-draft-fs", label: "Draft FS", purpose: "Preview draft financial statements generated from the FS Mapping", inputFields: [], buttons: ["Refresh Draft FS", "Export to Planning"], autoPulled: ["FS Mapping data", "TB data"], outputs: ["Draft BS", "Draft P&L", "Draft SoCF", "Draft SoCE", "Draft Notes"], commonErrors: ["Incomplete FS Mapping blocking Draft FS"] },
    ],
    workedExample: "For ABC & Co., download the AuditWise template, populate TB/GL/AP/AR/Bank sheets, and upload. System validates 245 accounts across all sheets, auto-classifies 89% using Manufacturing template, flags 27 unmapped accounts. Sync to core completes. FS Mapping auto-maps 220 accounts with 95%+ confidence. Draft FS generated for review.",
  },
  {
    key: "import-wizard",
    label: "Import Wizard",
    routePath: "/workspace/:id/import",
    phase: "Information Gathering",
    purpose: "Step-by-step wizard for uploading Excel data using the AuditWise template. Guides users through file selection, sheet validation, column mapping, data preview, and batch import with error handling.",
    prerequisites: ["Engagement created", "AuditWise Excel template downloaded and populated", "Data Intake module accessible"],
    isaReferences: ["ISA 230", "ISA 500"],
    roles: ["Staff", "Senior", "Manager"],
    approvals: ["Upload batch approval (Maker-Checker)"],
    locks: ["Import locked after batch approval"],
    tabs: [
      { key: "select-file", label: "Select File", purpose: "Upload the AuditWise Excel template and validate file structure", inputFields: ["Excel file upload (.xlsx)"], buttons: ["Browse", "Upload", "Download Template"], autoPulled: ["Engagement period", "Currency"], outputs: ["File validation result"], commonErrors: ["Wrong file format", "Corrupted file", "Missing required sheets"] },
      { key: "sheet-validation", label: "Sheet Validation", purpose: "Validate each sheet (TB, GL, AP, AR, Bank, Confirmations) for required columns and data integrity", inputFields: [], buttons: ["Validate All", "Skip Sheet"], autoPulled: ["Sheet headers from uploaded file"], outputs: ["Per-sheet validation report", "Column mapping preview"], commonErrors: ["Missing required columns", "Data type mismatches", "Empty sheets"] },
      { key: "data-preview", label: "Data Preview", purpose: "Preview parsed data from each sheet with row counts, totals, and sample records before import", inputFields: ["Row selection for exclusion"], buttons: ["Preview", "Exclude Rows", "Proceed to Import"], autoPulled: ["Parsed data from all sheets"], outputs: ["Data preview with statistics"], commonErrors: ["Unexpected row count", "Duplicate records detected"] },
      { key: "import-execute", label: "Import", purpose: "Execute the batch import with progress tracking and error log", inputFields: [], buttons: ["Start Import", "Retry Failed", "Cancel"], autoPulled: ["Validated data from preview"], outputs: ["Import batch record", "Import success/failure log"], commonErrors: ["Partial import failure", "Database constraint violations"] },
    ],
    workedExample: "For ABC & Co., staff downloads the AuditWise template, populates 245 TB rows and 1,200 GL entries. Import wizard validates all 6 sheets, previews data, and imports in 12 seconds. 3 GL rows flagged for duplicate codes; staff corrects and re-imports.",
  },
  {
    key: "tb-review",
    label: "Trial Balance Review",
    routePath: "/workspace/:id/tb-review",
    phase: "Information Gathering",
    purpose: "Dedicated Trial Balance review workspace for validating uploaded TB data, checking debit/credit balance, comparing with prior year, identifying unusual movements, and preparing TB for planning phase consumption.",
    prerequisites: ["TB data imported via Import Wizard or Data Intake"],
    isaReferences: ["ISA 315", "ISA 520", "ISA 500"],
    roles: ["Senior", "Manager"],
    approvals: ["TB review sign-off"],
    locks: ["TB locked after review approval"],
    tabs: [
      { key: "balance-check", label: "Balance Check", purpose: "Verify TB debit total equals credit total with variance analysis", inputFields: [], buttons: ["Refresh Totals", "Flag Imbalance"], autoPulled: ["TB debit total", "TB credit total"], outputs: ["Balance status (balanced/imbalanced)", "Variance amount"], commonErrors: ["TB does not balance", "Rounding issues"] },
      { key: "movement-analysis", label: "Movement Analysis", purpose: "Compare current year TB with prior year to identify significant movements and unusual fluctuations", inputFields: ["Prior year TB (editable)", "Threshold percentage"], buttons: ["Run Analysis", "AI Flagging", "Export"], autoPulled: ["Current year TB", "Prior year TB from previous engagement"], outputs: ["Movement analysis report", "Flagged accounts list"], commonErrors: ["Missing prior year data", "Threshold set too low"] },
      { key: "account-review", label: "Account Review", purpose: "Line-by-line review of TB accounts with drill-down to GL detail", inputFields: ["Review notes per account", "Reclassification entries"], buttons: ["Drill to GL", "Add Note", "Reclassify"], autoPulled: ["TB line items", "GL detail per account"], outputs: ["Reviewed TB with notes", "Reclassification journal"], commonErrors: ["Missing review notes on material accounts"] },
    ],
    workedExample: "For ABC & Co., TB review confirms debit/credit balance at PKR 52.3M. Movement analysis flags 8 accounts with >30% year-on-year change including Trade Receivables (+45%) and Inventory (-22%). Senior adds review notes and Manager approves.",
  },
  {
    key: "review-mapping",
    label: "FS Mapping Workflow",
    routePath: "/workspace/:id/requisition?tab=review-coa&subtab=mapping",
    phase: "Information Gathering",
    purpose: "Step-based 3-panel FS Mapping workflow with AI-powered auto-map, confidence scores, exceptions queue with guided fixes, live reconciliation ribbon (TB total vs mapped total), Approve & Lock with versioning, and version trail timeline.",
    prerequisites: ["CoA imported via Data Intake", "TB uploaded and reviewed", "GL data synced"],
    isaReferences: ["ISA 315", "ISA 500"],
    roles: ["Senior", "Manager"],
    approvals: ["Mapping approval", "Approve & Lock gate"],
    locks: ["Mapping locked after Approve & Lock", "Version snapshot created on lock"],
    tabs: [
      { key: "auto-map", label: "AI Auto-Map", purpose: "AI-powered automatic mapping of CoA accounts to FS line items with confidence scores per match", inputFields: ["Confidence threshold slider", "FS template selection"], buttons: ["Run Auto-Map", "Accept All High-Confidence", "Reset"], autoPulled: ["CoA accounts", "TB balances", "Industry FS templates"], outputs: ["Mapped accounts with confidence scores", "Mapping coverage percentage"], commonErrors: ["Low-confidence matches need manual review", "Missing FS template for industry"] },
      { key: "exceptions", label: "Exceptions Queue", purpose: "Guided fix queue for low-confidence or unmapped accounts with AI suggestions and manual override", inputFields: ["FS line item override", "Manual account assignment", "Rejection reason"], buttons: ["Accept Suggestion", "Override", "Skip", "Flag for Review"], autoPulled: ["Unmapped accounts", "AI alternative suggestions"], outputs: ["Resolved exceptions log", "Remaining exception count"], commonErrors: ["Skipped exceptions blocking approval", "Incorrect manual override"] },
      { key: "reconciliation", label: "Reconciliation Ribbon", purpose: "Live reconciliation view showing TB total vs mapped total with variance drill-down", inputFields: [], buttons: ["Refresh Totals", "Drill into Variance"], autoPulled: ["TB debit/credit totals", "Mapped account totals"], outputs: ["Reconciliation status (balanced/unbalanced)", "Variance breakdown"], commonErrors: ["Variance caused by unmapped accounts", "Rounding differences"] },
      { key: "approve-lock", label: "Approve & Lock", purpose: "Final approval gate for FS Mapping with version snapshot creation", inputFields: ["Approval comments"], buttons: ["Approve & Lock", "Request Changes"], autoPulled: ["Mapping coverage", "Reconciliation status", "Exception count"], outputs: ["Locked mapping version", "Version snapshot"], commonErrors: ["Outstanding exceptions blocking approval", "Reconciliation imbalance"] },
      { key: "version-trail", label: "Version Trail", purpose: "Timeline of all mapping versions with diff comparison and rollback capability", inputFields: [], buttons: ["Compare Versions", "Rollback to Version"], autoPulled: ["All locked versions with timestamps"], outputs: ["Version diff report", "Rollback confirmation"], commonErrors: ["Rollback requires Manager approval"] },
    ],
    workedExample: "For ABC & Co., AI auto-maps 220 of 245 accounts with 90%+ confidence. 18 accounts flagged in exceptions queue; reviewer accepts 15 AI suggestions, manually overrides 3. Reconciliation ribbon shows TB total PKR 52.3M = mapped total PKR 52.3M (balanced). Manager approves and locks as Version 1.0.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 5: Planning (5.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "planning",
    label: "Planning & Risk Assessment",
    routePath: "/workspace/:id/planning",
    phase: "Planning",
    purpose: "Core planning phase covering materiality calculation, risk assessment, financial statement analysis (populated from FS Mapping data flow in Data Intake), audit strategy determination, Draft FS generation, and procedure planning per ISA 300/315/320.",
    prerequisites: ["Pre-Planning completed and approved", "Information Gathering completed (TB/GL uploaded, FS Mapping approved)"],
    isaReferences: ["ISA 300", "ISA 315", "ISA 320", "ISA 330", "ISA 240", "ISA 450", "ISA 530"],
    roles: ["Senior", "Manager", "Partner"],
    approvals: ["Materiality approval", "Risk assessment approval", "Audit plan approval"],
    locks: ["Materiality locked after approval", "Risk matrix locked after review"],
    tabs: [
      { key: "financial-statements", label: "Financial Statements", purpose: "View and analyze the 5 financial statements (BS, P&L, SoCF, SoCE, Notes)", inputFields: ["Prior year figures (editable)"], buttons: ["Refresh FS", "Print FS"], autoPulled: ["TB data mapped to FS line items", "CoA classifications"], outputs: ["Draft Financial Statements", "FS analysis"], commonErrors: ["Missing FS head mappings"] },
      { key: "entity-controls", label: "Understanding Entity & Internal Controls (ISA 315)", purpose: "Document entity understanding, business environment, and internal control assessment", inputFields: ["Entity background", "Industry environment", "Control walkthrough"], buttons: ["Generate AI Content", "Add Walkthrough"], autoPulled: ["Client history", "Industry data"], outputs: ["Entity understanding record", "Control assessment"], commonErrors: ["Incomplete walkthrough documentation"] },
      { key: "risk-assessment", label: "Risk Assessment (ISA 315 & 240)", purpose: "Identify and assess risks of material misstatement at FS and assertion levels", inputFields: ["Risk descriptions", "Likelihood", "Impact", "Response strategy"], buttons: ["AI Risk Identification", "Add Risk", "Approve Risk Matrix"], autoPulled: ["FS Heads", "Industry risks", "Prior year findings"], outputs: ["Risk register", "ROMM matrix", "Fraud risk analysis"], commonErrors: ["Missing assertion-level risks", "Unlinked FS heads"] },
      { key: "analytical-procedures", label: "Analytical Procedures (ISA 520)", purpose: "Perform preliminary analytical procedures and ratio analysis", inputFields: ["Expected values", "Threshold percentages"], buttons: ["Run Analysis", "AI Variance Explanation"], autoPulled: ["TB data", "Prior year data"], outputs: ["Analytical results", "Variance analysis"], commonErrors: ["Missing prior year data"] },
      { key: "materiality", label: "Materiality (ISA 320)", purpose: "Calculate overall materiality, performance materiality, and trivial threshold using configurable benchmarks", inputFields: ["Benchmark selection", "Materiality percentage", "Professional judgment notes"], buttons: ["Calculate", "AI Analysis", "Approve Materiality"], autoPulled: ["Revenue", "Total Assets", "Profit Before Tax from FS"], outputs: ["MaterialitySet record", "8-step AI analysis"], commonErrors: ["Benchmark not selected", "Unreasonable percentage"] },
      { key: "strategy-approach", label: "Audit Strategy & Approach (ISA 300)", purpose: "Determine the overall audit approach and planned responses to assessed risks", inputFields: ["Strategy selections", "Scope decisions", "Controls reliance decisions"], buttons: ["AI Strategy Generation", "Approve Strategy"], autoPulled: ["Risk assessment", "Materiality", "Prior year approach"], outputs: ["Audit plan", "Strategy document"], commonErrors: ["Strategy not aligned with risk assessment"] },
      { key: "team-quality", label: "Team & Quality Management (ISA 220/ISQM 1)", purpose: "Assign audit team members with roles, responsibilities, and competence confirmation", inputFields: ["Team member selection", "Role assignment", "Hours budget", "Competence confirmation"], buttons: ["Add Member", "Set Budget"], autoPulled: ["Available staff", "Skill matrix"], outputs: ["Team allocation record", "Budget summary"], commonErrors: ["Insufficient team coverage", "Missing competence confirmation"] },
      { key: "sampling", label: "Sampling (ISA 530)", purpose: "Define sampling methodology, calculate sample sizes, and generate sample selections", inputFields: ["Population definition", "Sampling method", "Confidence level"], buttons: ["Calculate Sample Size", "Generate Samples", "AI Recommendations"], autoPulled: ["Population from GL/TB", "Materiality thresholds"], outputs: ["Sampling frames", "Sample selections"], commonErrors: ["Population incomplete", "Sample too small for risk level"] },
      { key: "audit-program", label: "Audit Program (ISA 300)", purpose: "Generate and customize audit procedures for each FS head and assertion", inputFields: ["Procedure selection", "Custom procedures", "Timing"], buttons: ["Generate Program", "Push to Execution"], autoPulled: ["Risk responses", "Sampling parameters", "FS heads"], outputs: ["Audit program", "Procedure assignments"], commonErrors: ["Missing procedures for high-risk areas"] },
      { key: "specialized-areas", label: "Specialized Planning Areas", purpose: "Address specialized audit considerations including related parties, going concern, and subsequent events", inputFields: ["Related party details", "Going concern indicators", "Subsequent events"], buttons: ["Add Entry", "AI Assessment"], autoPulled: ["Entity data", "Financial indicators"], outputs: ["Specialized area documentation"], commonErrors: ["Missing related party disclosures"] },
      { key: "tcwg-communication", label: "Communication with TCWG (ISA 260)", purpose: "Plan and document communications with Those Charged With Governance", inputFields: ["Communication topics", "TCWG identification", "Communication schedule"], buttons: ["Generate Communication Plan"], autoPulled: ["Audit findings", "Risk assessment"], outputs: ["TCWG communication plan", "Communication log"], commonErrors: ["Missing TCWG identification"] },
      { key: "quality-control", label: "Quality Control & Planning Review (ISA 220/ISQM 1 & 2)", purpose: "Quality control review of the planning phase with documentation and sign-off", inputFields: ["Review comments", "Quality objectives"], buttons: ["Complete Review", "Approve Planning"], autoPulled: ["All planning section statuses"], outputs: ["Quality control record", "Planning approval"], commonErrors: ["Incomplete review documentation"] },
    ],
    workedExample: "For ABC & Co., materiality set at 2% of Revenue (PKR 5.2M). AI identifies 12 significant risks including inventory valuation (HIGH) and revenue recognition (HIGH). Strategy: substantive approach for all FS heads.",
  },
  {
    key: "audit-health-dashboard",
    label: "AI Audit Health Dashboard",
    routePath: "/workspace/:id/audit-health",
    phase: "Planning",
    purpose: "AI-powered real-time health monitoring dashboard for the audit engagement. Provides overall readiness score, phase completion tracking, risk heat maps, bottleneck identification, and proactive AI recommendations across all audit phases.",
    prerequisites: ["Engagement active", "Planning phase started or later"],
    isaReferences: ["ISQM 1", "ISA 220", "ISA 300", "ISA 315"],
    roles: ["Senior", "Manager", "Partner"],
    approvals: [],
    locks: [],
    tabs: [
      { key: "health-score", label: "Health Score", purpose: "Overall engagement health score with breakdown by phase, quality indicators, and trend analysis", inputFields: [], buttons: ["Refresh Score", "Export Report"], autoPulled: ["Phase completion percentages", "Outstanding items", "Risk indicators", "Evidence coverage"], outputs: ["Overall health score (0-100)", "Phase-by-phase breakdown", "Trend chart"], commonErrors: [] },
      { key: "bottlenecks", label: "Bottlenecks", purpose: "AI-identified bottlenecks and blockers across the engagement with recommended actions", inputFields: [], buttons: ["Run AI Analysis", "Assign Action"], autoPulled: ["Overdue procedures", "Unsigned work papers", "Missing evidence", "Pending approvals"], outputs: ["Bottleneck list with severity", "AI recommendations"], commonErrors: ["Stale data if phases not updated"] },
      { key: "risk-heatmap", label: "Risk Heat Map", purpose: "Visual heat map of risk distribution across FS heads and assertions", inputFields: [], buttons: ["Toggle View (FS Head / Assertion / Phase)"], autoPulled: ["Risk assessment data", "Execution results"], outputs: ["Interactive risk heat map"], commonErrors: ["Risk assessment not completed"] },
      { key: "compliance-tracker", label: "ISA Compliance", purpose: "Track ISA compliance status across all applicable standards for the engagement", inputFields: [], buttons: ["Generate Compliance Report"], autoPulled: ["ISA requirements", "Completed procedures", "Documentation status"], outputs: ["ISA compliance matrix", "Gap analysis"], commonErrors: ["Incomplete procedure documentation"] },
    ],
    workedExample: "For ABC & Co., AI Health Dashboard shows overall score of 78/100. Pre-Planning (100%), Planning (95%), Execution (62%). AI identifies 3 bottlenecks: 2 unsigned Revenue work papers, 1 missing bank confirmation response. Risk heat map highlights Inventory (HIGH) and Revenue (HIGH) as focus areas.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 6: Execution (6.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "fs-heads",
    label: "FS Head Procedures",
    routePath: "/workspace/:id/fs-heads",
    phase: "Execution",
    purpose: "Per-FS-Head working papers with assertion matrix, procedures, evidence, sampling, and sign-off for each financial statement line item.",
    prerequisites: ["Planning completed", "FS heads generated from Planning", "Procedures assigned via Audit Program"],
    isaReferences: ["ISA 315", "ISA 330", "ISA 500"],
    roles: ["Staff", "Senior", "Manager", "Partner"],
    approvals: ["Staff→Prepared", "Manager→Reviewed", "Partner→Approved"],
    locks: ["FS Head locked after Partner sign-off"],
    tabs: [
      { key: "assertions", label: "Assertion Matrix", purpose: "Map risks to assertions (CAVR-EC framework) with risk ratings", inputFields: ["Assertion responses", "Risk overrides"], buttons: ["Auto-Calculate ROMM"], autoPulled: ["Risk assessment", "FS head details"], outputs: ["Assertion-level risk matrix"], commonErrors: ["Missing assertion responses"] },
      { key: "procedures", label: "Audit Program", purpose: "FS-head-specific procedures from the audit program", inputFields: ["Procedure results", "Timing"], buttons: ["Execute", "Link Evidence"], autoPulled: ["Procedures from Planning"], outputs: ["Procedure completion status"], commonErrors: ["Unexecuted procedures"] },
      { key: "evidence", label: "Evidence", purpose: "Attach and organize audit evidence per ISA 500", inputFields: ["Evidence files", "Description", "ISA category"], buttons: ["Upload Evidence", "Link to Procedure"], autoPulled: [], outputs: ["Evidence register"], commonErrors: ["Evidence not linked to procedure"] },
      { key: "notes", label: "Notes", purpose: "Working paper notes and observations", inputFields: ["Note content", "References"], buttons: ["Add Note"], autoPulled: [], outputs: ["Working paper notes"], commonErrors: [] },
    ],
    workedExample: "For ABC & Co. Revenue FS Head: Assertions mapped (Occurrence=HIGH, Completeness=MEDIUM). 5 procedures executed. 12 evidence items linked. Manager signs off.",
  },
  {
    key: "execution",
    label: "Execution",
    routePath: "/workspace/:id/execution",
    phase: "Execution",
    purpose: "Execute audit procedures, record findings, perform tests of controls and substantive testing, and document evidence.",
    prerequisites: ["Planning completed", "Audit program generated and pushed to execution"],
    isaReferences: ["ISA 330", "ISA 500", "ISA 530", "ISA 505", "ISA 520"],
    roles: ["Staff", "Senior", "Manager"],
    approvals: ["Work paper review", "Section sign-off"],
    locks: ["Procedures locked after Manager review"],
    tabs: [
      { key: "procedures", label: "Audit Procedures", purpose: "Execute planned audit procedures from the audit program", inputFields: ["Procedure results", "Exceptions noted", "Sample details"], buttons: ["Start Procedure", "Record Result", "Attach Evidence"], autoPulled: ["Audit program from Planning", "Sample selections"], outputs: ["Execution results", "Exception reports"], commonErrors: ["Missing evidence attachment", "Incomplete procedures"] },
      { key: "controls", label: "Controls Testing", purpose: "Test operating effectiveness of internal controls", inputFields: ["Control descriptions", "Test results", "Deviations"], buttons: ["Test Control", "Record Deviation"], autoPulled: ["Controls from risk assessment"], outputs: ["Controls test results", "Deviation summary"], commonErrors: ["Insufficient sample for controls testing"] },
      { key: "substantive", label: "Substantive Testing", purpose: "Perform substantive analytical procedures and tests of details", inputFields: ["Test details", "Results", "Conclusions"], buttons: ["Perform Test", "Record Finding"], autoPulled: ["Sampling frames", "Population data"], outputs: ["Substantive test results", "Findings register"], commonErrors: ["Misstatement not quantified"] },
    ],
    workedExample: "For ABC & Co., Staff executes 47 procedures across 11 FS heads. 3 exceptions found in revenue testing. Manager reviews and approves work papers.",
  },
  {
    key: "evidence",
    label: "Evidence Vault",
    routePath: "/workspace/:id/evidence",
    phase: "Execution",
    purpose: "Central repository for all audit evidence across phases with ISA 500 compliance tracking, cross-referencing, and completeness checks.",
    prerequisites: ["Engagement active", "Execution phase in progress"],
    isaReferences: ["ISA 500", "ISA 230"],
    roles: ["All roles"],
    approvals: ["Evidence sufficiency review by Manager"],
    locks: ["Evidence vault locked after Finalization sign-off"],
    tabs: [],
    workedExample: "For ABC & Co., Evidence Vault contains 89 items across all phases. ISA 500 compliance dashboard shows 95% evidence coverage.",
  },
  {
    key: "observations",
    label: "Observation Board",
    routePath: "/workspace/:id/observations",
    phase: "Execution",
    purpose: "Track audit findings, misstatements, and observations with severity classification, management response tracking, and impact assessment.",
    prerequisites: ["Execution in progress", "FS Head procedures started"],
    isaReferences: ["ISA 450", "ISA 260"],
    roles: ["Senior", "Manager", "Partner"],
    approvals: ["Management response required", "Partner conclusion"],
    locks: ["Observations locked after Finalization completion"],
    tabs: [],
    workedExample: "For ABC & Co., 3 observations recorded: inventory count variance (Material), revenue cutoff (Significant), depreciation calculation (Trivial). Management agrees to adjust inventory.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 7: Finalization (7.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "finalization",
    label: "Finalization",
    routePath: "/workspace/:id/finalization",
    phase: "Finalization",
    purpose: "Complete the audit engagement with adjusted financial statements, subsequent events review, going concern assessment, audit opinion, Finalization Control Board with AI risk scoring, and file closure. Includes a Standards Gate that blocks Partner approval when blockers remain (e.g. HIGH-risk unresolved issues, pending execution items, or missing evidence).",
    prerequisites: ["Execution completed", "All FS heads signed off", "Observations resolved or concluded"],
    isaReferences: ["ISA 450", "ISA 560", "ISA 570", "ISA 700", "ISA 701", "ISA 706"],
    roles: ["Manager", "Partner"],
    approvals: ["Audit opinion approval", "Finalization Control Board review", "Standards Gate clearance", "File closure approval"],
    locks: ["Engagement locked after Partner sign-off", "Standards Gate blocks approval if HIGH-risk issues, pending items, or missing evidence exist"],
    tabs: [
      { key: "adjusted-fs", label: "Adjusted Financial Statements", purpose: "View all 5 financial statements with post-audit adjustments applied", inputFields: [], buttons: ["Refresh from Planning"], autoPulled: ["Draft FS from Planning", "Adjustments from Observations"], outputs: ["Adjusted BS, P&L, SoCF, SoCE, Notes"], commonErrors: ["Unapproved adjustments"] },
      { key: "subsequent-events", label: "Subsequent Events (ISA 560)", purpose: "Identify and evaluate events occurring after the reporting date", inputFields: ["Event description", "Date", "Type (adjusting/non-adjusting)", "Impact"], buttons: ["Add Event", "AI Review"], autoPulled: [], outputs: ["Subsequent events register"], commonErrors: ["Missing event classification"] },
      { key: "going-concern", label: "Going Concern (ISA 570)", purpose: "Assess the entity's ability to continue as a going concern", inputFields: ["Indicators checklist", "Management plans", "Conclusion"], buttons: ["AI Assessment", "Approve Conclusion"], autoPulled: ["Financial indicators from FS"], outputs: ["Going concern conclusion"], commonErrors: ["Incomplete indicator assessment"] },
      { key: "checklist", label: "Completion Checklist", purpose: "Final audit completion checklist ensuring all requirements met", inputFields: ["Checklist responses", "Remarks"], buttons: ["Auto-Check", "Complete"], autoPulled: ["Phase completion statuses"], outputs: ["Completion report"], commonErrors: ["Outstanding items"] },
      { key: "audit-opinion", label: "Audit Opinion (ISA 700)", purpose: "Form and document the audit opinion", inputFields: ["Opinion type", "Basis for modification", "Emphasis of matter", "Other matter"], buttons: ["Generate Opinion", "Approve"], autoPulled: ["Misstatement summary", "Going concern conclusion"], outputs: ["Audit opinion document"], commonErrors: ["Opinion not aligned with findings"] },
      { key: "control-board", label: "Finalization Control Board", purpose: "AI-assisted dashboard showing pending execution items, unadjusted misstatements (ISA 450), Key Audit Matters (ISA 701), and a deterministic risk score (0-100). Role-scoped views: Staff sees own items, Manager sees team, Partner sees executive summary. Must be generated before Partner can approve Finalization.", inputFields: [], buttons: ["Generate Board", "Regenerate"], autoPulled: ["Pending execution items", "Misstatement register", "KAM items", "Risk assessment data"], outputs: ["Risk score (0-100) with LOW/MEDIUM/HIGH rating", "Top 3 risk drivers", "Recommended actions", "Stat tiles for pending items, misstatements, KAMs"], commonErrors: ["Board not generated before attempting approval", "HIGH risk with unresolved issues blocks Standards Gate"] },
      { key: "sign-off", label: "Sign-off & Closure", purpose: "Final partner sign-off, engagement closure, and file archival. Standards Gate automatically blocks approval if: Finalization Board not generated, HIGH risk with unresolved high-severity issues, pending execution items > 0, or missing evidence.", inputFields: ["Approval comments"], buttons: ["Sign Off", "Lock Engagement", "Archive"], autoPulled: ["All approval statuses", "Finalization Board results", "Standards Gate check results"], outputs: ["Signed audit report", "Archived engagement file"], commonErrors: ["Standards Gate blockers preventing closure", "Missing Finalization Board"] },
    ],
    workedExample: "For ABC & Co., Adjusted FS shows 2 adjustments applied. No subsequent events. Going concern: no material uncertainty. Finalization Control Board generated: risk score 35/100 (LOW), 0 pending execution items, 1 unadjusted misstatement below PM, 2 KAMs documented. Standards Gate: all checks pass. Unmodified opinion issued. Partner signs off and locks engagement.",
  },
  {
    key: "engagement-control",
    label: "Audit Control Pack",
    routePath: "/workspace/:id/control",
    phase: "Finalization",
    purpose: "Centralized control pack for the engagement providing a consolidated view of audit plan, materiality settings, procedures matrix, sampling frames, execution results, and lock gate status across all phases.",
    prerequisites: ["Planning completed", "Execution completed", "Finalization in progress"],
    isaReferences: ["ISA 300", "ISA 315", "ISA 320", "ISA 330", "ISA 530"],
    roles: ["Manager", "Partner"],
    approvals: ["Partner approval for control pack sign-off"],
    locks: ["Control pack locked after Partner sign-off"],
    tabs: [
      { key: "audit-plan", label: "Audit Plan", purpose: "Consolidated audit plan summary with scope, approach, timeline, and team allocation", inputFields: [], buttons: ["Refresh from Planning", "Export Plan"], autoPulled: ["Audit strategy", "Team allocation", "Timeline from Planning"], outputs: ["Consolidated audit plan document"], commonErrors: ["Plan out of sync with latest planning updates"] },
      { key: "materiality-set", label: "Materiality Set", purpose: "View approved materiality levels (overall, performance, trivial) with benchmark details", inputFields: [], buttons: ["View Calculation", "Export"], autoPulled: ["Materiality from Planning"], outputs: ["Materiality summary"], commonErrors: ["Materiality not yet approved"] },
      { key: "procedures-matrix", label: "Procedures Matrix", purpose: "Cross-reference matrix of FS heads, assertions, risks, and planned procedures", inputFields: [], buttons: ["Refresh Matrix", "Export"], autoPulled: ["FS heads", "Risk assessment", "Audit program"], outputs: ["Procedures-to-risk matrix"], commonErrors: ["Gaps in procedure coverage for high-risk areas"] },
      { key: "sampling-frame", label: "Sampling Frames", purpose: "Overview of all sampling frames, sample sizes, and selection status", inputFields: [], buttons: ["View Selections", "Export"], autoPulled: ["Sampling from Planning"], outputs: ["Sampling summary"], commonErrors: ["Incomplete sample selections"] },
      { key: "execution-results", label: "Execution Results", purpose: "Summary of execution outcomes, exceptions, and findings", inputFields: [], buttons: ["Refresh Results", "Export"], autoPulled: ["Execution phase results", "Exception reports"], outputs: ["Execution summary dashboard"], commonErrors: ["Incomplete execution data"] },
      { key: "lock-gate", label: "Lock Gate", purpose: "Phase gate status and lock controls for the engagement", inputFields: ["Gate approval comments"], buttons: ["Lock Phase", "Unlock (Partner only)"], autoPulled: ["Phase completion statuses", "Outstanding items"], outputs: ["Gate status report", "Lock audit trail"], commonErrors: ["Outstanding items preventing gate lock"] },
    ],
    workedExample: "For ABC & Co., Control Pack shows audit plan approved, materiality at PKR 5.2M, 47 procedures across 11 FS heads, 6 sampling frames generated. Manager reviews procedures matrix and confirms full coverage. Partner locks the planning gate.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 8: Reporting & Deliverables (8.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "reports",
    label: "Reports",
    routePath: "/reports",
    phase: "Reporting & Deliverables",
    purpose: "Generate comprehensive reports including engagement progress, mapping coverage, TB/GL reconciliation, sampling, adjustments, and audit trail.",
    prerequisites: ["Finalization completed or in progress", "Active engagements with data"],
    isaReferences: ["ISA 230"],
    roles: ["Manager", "Partner", "Admin"],
    approvals: ["Report approval by Partner for external distribution"],
    locks: ["Final reports locked after Partner sign-off"],
    tabs: [],
    workedExample: "Manager generates Engagement Progress report for ABC & Co. showing 85% completion with 2 overdue procedures.",
  },
  {
    key: "deliverables",
    label: "Deliverables & Document Generation",
    routePath: "/workspace/:id/deliverables",
    phase: "Reporting & Deliverables",
    purpose: "Comprehensive print-ready document generation engine. Produces formatted audit reports, financial statements, working paper packs, management letters, and compliance documentation with customizable templates and branding.",
    prerequisites: ["Relevant phase work completed", "Deliverables reviewed"],
    isaReferences: ["ISA 230", "ISA 700", "ISA 706"],
    roles: ["Senior", "Manager", "Partner"],
    approvals: ["Print approval for final documents"],
    locks: ["Printed documents versioned and locked after approval"],
    tabs: [
      { key: "template-selection", label: "Template Selection", purpose: "Select document template and configure formatting options including firm branding, headers, and page layout", inputFields: ["Template type", "Firm logo", "Header/Footer text", "Page orientation"], buttons: ["Select Template", "Preview Layout", "Upload Logo"], autoPulled: ["Firm branding settings", "Engagement details"], outputs: ["Configured print template"], commonErrors: ["Missing firm logo", "Incorrect page margins"] },
      { key: "document-builder", label: "Document Builder", purpose: "Build the document by selecting sections, appendices, and supporting schedules to include", inputFields: ["Section selection (checkboxes)", "Custom cover page text", "Table of contents options"], buttons: ["Build Document", "Add Section", "Remove Section", "Reorder"], autoPulled: ["Available sections from all phases", "Financial statements", "Working papers"], outputs: ["Document structure preview"], commonErrors: ["Missing required sections", "Section order incorrect"] },
      { key: "preview-export", label: "Preview & Export", purpose: "Preview the generated document and export as PDF or print", inputFields: [], buttons: ["Preview", "Export PDF", "Print", "Email Document"], autoPulled: ["Built document content"], outputs: ["Generated PDF document", "Print job record"], commonErrors: ["Formatting issues in preview", "Large file size"] },
    ],
    workedExample: "For ABC & Co., Manager selects the Statutory Audit Report template. Includes audit opinion, adjusted FS (all 5 statements), notes, management letter, and appendices. Preview confirms 48 pages. Exports as PDF and emails to Partner for final review.",
  },
  {
    key: "outputs",
    label: "Outputs",
    routePath: "/workspace/:id/outputs",
    phase: "Reporting & Deliverables",
    purpose: "Central registry of all generated deliverables tracking outputs by phase, status, version, and ISA tags with evidence linking.",
    prerequisites: ["Relevant phase work completed"],
    isaReferences: ["ISA 230"],
    roles: ["Senior", "Manager", "Partner"],
    approvals: ["Output review by Manager"],
    locks: ["Outputs locked after final engagement sign-off"],
    tabs: [],
    workedExample: "For ABC & Co., 15 outputs generated: Audit Plan, Risk Matrix, Materiality Memo, 11 FS Head working papers, Summary of Misstatements.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 9: Quality Review (EQCR) (9.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "eqcr",
    label: "Quality Review (EQCR)",
    routePath: "/workspace/:id/eqcr",
    phase: "Quality Review (EQCR)",
    purpose: "Engagement Quality Control Review per ISQM 1 / ISA 220. Independent partner reviews the entire audit file for quality and compliance.",
    prerequisites: ["Finalization completed", "EQCR reviewer assigned", "Audit Control Pack signed off"],
    isaReferences: ["ISA 220", "ISQM 1", "ISQM 2"],
    roles: ["EQCR Reviewer", "Partner"],
    approvals: ["EQCR approval/rejection"],
    locks: ["Engagement locked after EQCR approval"],
    tabs: [],
    workedExample: "For ABC & Co., EQCR reviewer examines 15 quality checkpoints. 2 queries raised, both resolved by engagement partner. EQCR approved.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 10: Inspection & Archiving (10.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "inspection",
    label: "Inspection",
    routePath: "/workspace/:id/inspection",
    phase: "Inspection & Archiving",
    purpose: "AOB/ICAP style quality inspection dashboard for post-engagement monitoring and compliance verification.",
    prerequisites: ["Engagement completed", "EQCR completed", "Engagement archived"],
    isaReferences: ["ISQM 1"],
    roles: ["Admin", "Quality Reviewer"],
    approvals: ["Inspection findings approval by Quality Reviewer"],
    locks: ["Inspection record locked after final report"],
    tabs: [],
    workedExample: "For ABC & Co., inspection checklist auto-generated with 45 items. 42 satisfactory, 3 require follow-up.",
  },
  {
    key: "inspection-dashboard",
    label: "Inspection Dashboard",
    routePath: "/workspace/:id/qcr-dashboard",
    phase: "Inspection & Archiving",
    purpose: "Firm-wide inspection management dashboard for AOB/ICAP quality control reviews. Provides an overview of all engagements under inspection, compliance scoring, deficiency tracking, and remediation monitoring across the firm.",
    prerequisites: ["Admin or Quality Reviewer role", "Completed engagements available for inspection", "Engagement-level inspections initiated"],
    isaReferences: ["ISQM 1", "ISA 220"],
    roles: ["Admin", "Quality Reviewer", "Partner"],
    approvals: ["Inspection findings approval"],
    locks: ["Inspection locked after final report issuance"],
    tabs: [
      { key: "overview", label: "Overview", purpose: "Firm-wide inspection status with engagement list, inspection progress, and aggregate compliance scores", inputFields: [], buttons: ["Start New Inspection", "Filter by Year", "Export Dashboard"], autoPulled: ["All completed engagements", "Prior inspection history", "EQCR results"], outputs: ["Inspection summary dashboard", "Compliance score card"], commonErrors: ["Engagements not marked as completed"] },
      { key: "checklist-review", label: "Checklist Review", purpose: "Detailed inspection checklist with AOB/ICAP quality control review items per engagement", inputFields: ["Checklist responses", "Inspector comments", "Rating per item"], buttons: ["Auto-Generate Checklist", "Complete Section", "Flag Deficiency"], autoPulled: ["Engagement working papers", "EQCR outcomes", "Audit procedures"], outputs: ["Completed inspection checklist", "Deficiency register"], commonErrors: ["Incomplete checklist sections", "Missing supporting references"] },
      { key: "findings", label: "Findings & Remediation", purpose: "Track inspection findings, root cause analysis, and remediation action plans with status monitoring", inputFields: ["Finding description", "Severity", "Root cause", "Remediation plan", "Responsible person", "Target date"], buttons: ["Log Finding", "Assign Remediation", "Mark Resolved", "Generate Report"], autoPulled: ["Checklist deficiencies"], outputs: ["Findings register", "Remediation tracker", "Inspection report"], commonErrors: ["Overdue remediation actions", "Missing root cause analysis"] },
      { key: "reporting", label: "Inspection Report", purpose: "Generate the formal inspection report with findings summary, recommendations, and follow-up actions", inputFields: ["Report narrative", "Recommendations"], buttons: ["Generate Report", "Export PDF", "Submit to AOB/ICAP"], autoPulled: ["All findings", "Remediation status", "Compliance scores"], outputs: ["Formal inspection report (PDF)", "Submission record"], commonErrors: ["Open findings not addressed in report"] },
    ],
    workedExample: "Quality Reviewer opens Inspection Dashboard showing 5 engagements for FY2025 review. ABC & Co. inspection: 45-item checklist completed, 3 deficiencies found (documentation gaps). Remediation plans assigned to engagement partner with Q2 deadline. Inspection report generated and submitted to AOB.",
  },

  // ═══════════════════════════════════════════════════════════════
  // Phase 11: Cross-Phase Tools (11.x)
  // ═══════════════════════════════════════════════════════════════
  {
    key: "dashboard",
    label: "Dashboard",
    routePath: "/",
    phase: "Cross-Phase Tools",
    purpose: "Central hub showing firm-wide overview, active engagements, team workload, and compliance health metrics.",
    prerequisites: ["Logged-in user account"],
    isaReferences: ["ISQM 1"],
    roles: ["All roles"],
    approvals: [],
    locks: [],
    tabs: [],
    workedExample: "On login, Admin sees 3 active engagements including ABC & Co. (FY2025) with 65% overall completion.",
  },
  {
    key: "workflow-health",
    label: "Workflow Health",
    routePath: "/workspace/:id/workflow-health",
    phase: "Cross-Phase Tools",
    purpose: "Diagnostic health check page for the engagement workflow pipeline. Runs automated checks across data upload, TB/GL integrity, FS mapping, materiality, risk assessment, sampling, execution, and finalization stages. Reports PASS/FAIL/WARN/SKIP status for each step with actionable hints for resolution.",
    prerequisites: ["Engagement active", "Any data uploaded or phases started"],
    isaReferences: ["ISA 230", "ISA 315", "ISA 320", "ISA 330"],
    roles: ["Senior", "Manager", "Partner", "Admin"],
    approvals: [],
    locks: [],
    tabs: [],
    workedExample: "For ABC & Co., Workflow Health runs 12 diagnostic checks. 10 PASS, 1 WARN (materiality not yet approved), 1 SKIP (inspection not started). Manager addresses the materiality warning by completing approval.",
  },
  {
    key: "sign-off-bar",
    label: "Unified Sign-Off Bar",
    routePath: "/workspace/:id/*",
    phase: "Cross-Phase Tools",
    purpose: "A single horizontal sign-off bar embedded in the header of every workspace page (Pre-Planning, Planning, Execution, FS Heads, Finalization). Shows the three-step approval workflow (Prepared, Reviewed, Approved) with colour-coded status badges (Draft=Grey, Prepared=Blue, Reviewed=Orange, Approved=Green). All timestamps display in PKT (Pakistan Standard Time). Enforces RBAC: only authorised roles can advance each step, and Separation of Duties prevents the same user from both preparing and reviewing. When a section reaches Approved status, an 'Approved - Read Only' badge appears and all inputs on the page are disabled automatically.",
    prerequisites: ["Engagement active", "User assigned to the engagement team"],
    isaReferences: ["ISA 220", "ISA 230", "ISQM 1"],
    roles: ["Staff", "Senior", "Manager", "Partner"],
    approvals: ["Staff/Senior can Prepare", "Manager can Review", "Partner can Approve", "Separation of Duties enforced (preparer cannot review their own work)"],
    locks: ["Page becomes read-only when section is Approved", "Partner can Unlock an approved section (reason mandatory, logged to audit trail)"],
    tabs: [],
    workedExample: "On the Planning page, Senior clicks 'Mark as Prepared' - status turns Blue (Prepared). Manager clicks 'Mark as Reviewed' - status turns Orange (Reviewed). Partner clicks 'Approve' - status turns Green and the page becomes read-only with 'Approved - Read Only' badge. All timestamps shown in PKT. Later, Partner unlocks with reason 'Additional risk identified' - page re-opens for editing.",
  },
  {
    key: "audit-trail",
    label: "Audit Trail",
    routePath: "/workspace/:id/audit-trail",
    phase: "Cross-Phase Tools",
    purpose: "Every sign-off action (prepare, review, approve, reject, return, lock, unlock) across both section-level and phase-level sign-offs is automatically logged with full context: user ID, user role, IP address, device information (browser/OS), previous status (beforeValue), new status (afterValue), and mandatory reason for unlocks and rejections. Provides a complete, tamper-evident record for regulatory inspection and quality review.",
    prerequisites: ["Engagement active"],
    isaReferences: ["ISA 230", "ISQM 1"],
    roles: ["Manager", "Partner", "Admin"],
    approvals: [],
    locks: ["Audit trail records are immutable - cannot be edited or deleted"],
    tabs: [],
    workedExample: "Partner views audit trail for ABC & Co. engagement. Sees chronological log: Senior prepared Planning at 14:32 PKT from 192.168.1.5 (Chrome/Windows), Manager reviewed Planning at 15:10 PKT, Partner approved at 16:45 PKT. Later, Partner unlocked Planning with reason 'New risk identified' - unlock logged with full before/after status and IP details.",
  },
  {
    key: "keyboard-shortcuts",
    label: "Keyboard Shortcuts",
    routePath: "/",
    phase: "Cross-Phase Tools",
    purpose: "Global keyboard shortcuts for rapid navigation and workflow efficiency. Press Ctrl+Shift+? (or Cmd+Shift+? on Mac) anytime to open the keyboard shortcuts reference panel. Includes shortcuts for search focus (Ctrl+/), navigation to key pages (Ctrl+Shift+H/E/C/G/S for Home/Engagements/Clients/User Guide/Settings), sidebar toggle (Ctrl+B), and workspace phase navigation (Alt+1 through Alt+8 to jump directly to Pre-Planning, Data Intake, Planning, Execution, FS Heads, Evidence, Finalization, and Deliverables).",
    prerequisites: ["Logged-in user"],
    isaReferences: [],
    roles: ["All roles"],
    approvals: [],
    locks: [],
    tabs: [],
    workedExample: "User presses Ctrl+Shift+? to view the full shortcuts list. Uses Alt+4 to jump directly to the Execution phase within the current engagement. Presses Ctrl+/ to focus the search bar. Uses Ctrl+Shift+E to navigate to the Engagements list without using the mouse.",
  },
  {
    key: "settings",
    label: "Settings",
    routePath: "/settings",
    phase: "Cross-Phase Tools",
    purpose: "User-level settings including theme preferences, notification settings, and display options.",
    prerequisites: ["Logged-in user"],
    isaReferences: [],
    roles: ["All roles"],
    approvals: [],
    locks: [],
    tabs: [],
    workedExample: "User selects dark mode with blue accent color. Notification preferences set for email + in-app.",
  },
  {
    key: "post-upload-workflow",
    label: "Post-Upload AI Workflow Dashboard",
    routePath: "/workspace/:id/post-upload-workflow",
    phase: "Information Gathering",
    purpose: "Unified exception-first workflow dashboard that orchestrates 8 post-upload audit phases. Each phase computes real-time gate status (PASSED, BLOCKED, IN_PROGRESS, APPROVED, NOT_STARTED), data quality scores, and AI-driven summaries from actual engagement data. Aggregates blockers and exceptions across all phases with severity taxonomy (S1 Blocker, S2 High, S3 Medium, S4 Low).",
    prerequisites: ["Engagement created", "Data uploaded or audit procedures initiated", "Staff or above role"],
    isaReferences: ["ISA 230", "ISA 315", "ISA 320", "ISA 330", "ISA 500", "ISA 530", "ISQM 1"],
    roles: ["Staff", "Senior", "Manager", "Partner", "Admin"],
    approvals: ["Phase gate approvals by Manager or Partner", "Exception resolution requires Staff or above"],
    locks: ["Phases lock upon APPROVED status", "Completion phase locked after finalization"],
    tabs: [
      {
        key: "dashboard",
        label: "Workflow Dashboard",
        purpose: "Aggregated view of all 8 phases with progress bar, blocker count, and phase cards showing gate status, score, AI summary, and highlights",
        inputFields: [],
        buttons: ["Scan Phase", "Resolve Exception", "Bulk Resolve"],
        autoPulled: ["Upload versions", "TB/GL batches", "Summary runs", "CoA accounts", "Materiality sets", "Risk assessments", "Populations", "Samples", "Working papers", "Completion deliverables"],
        outputs: ["Overall progress percentage", "Phase gate status cards", "Exception list with severity taxonomy", "AI-generated phase summaries"],
        commonErrors: ["Phase shows NOT_STARTED when underlying data exists in different tables", "Exception count includes resolved items if cache is stale"],
      },
      {
        key: "upload-profile",
        label: "Phase 1: Upload & Profiling",
        purpose: "Detects uploaded workbook sheets (TB, GL, CoA, Parties, Bank Accounts), reports missing required sheets, and shows period coverage",
        inputFields: [],
        buttons: ["Re-scan"],
        autoPulled: ["UploadVersion records", "TBBatch", "GLBatch", "CoAAccount count", "Party balances", "Bank accounts"],
        outputs: ["Sheets detected with row counts", "Missing sheets list", "Period range"],
        commonErrors: ["BLOCKED status when Trial Balance sheet is missing"],
      },
      {
        key: "data-quality",
        label: "Phase 2: Data Quality & Standardization",
        purpose: "Runs 4 core validation checks: TB arithmetic balance, GL debit/credit balance, TB-GL tie-out, and TB-GL totals consistency. Reports DQ score out of 100",
        inputFields: [],
        buttons: ["Run Validation", "Scan Exceptions"],
        autoPulled: ["SummaryRun results", "Validation exceptions"],
        outputs: ["DQ Score (0-100)", "Check results (PASS/FAIL)", "Row counts", "Exception breakdown by severity"],
        commonErrors: ["FAIL on TB arithmetic when opening balances have rounding differences"],
      },
      {
        key: "tb-gl-recon",
        label: "Phase 3: TB-GL Reconciliation",
        purpose: "Validates that Trial Balance movements reconcile to General Ledger totals. Shows reconciliation difference and AI-suggested root cause for discrepancies",
        inputFields: [],
        buttons: ["Re-reconcile"],
        autoPulled: ["SummaryRun reconciliation fields", "Reconciliation items from MappingSession"],
        outputs: ["Reconciliation status (PASS/FAIL)", "Movement difference amount", "Root cause suggestion", "Delta DR/CR"],
        commonErrors: ["BLOCKED when TB imported as closing-only without movement columns"],
      },
      {
        key: "fs-mapping",
        label: "Phase 4: FS Mapping & Lead Schedules",
        purpose: "Tracks Chart of Accounts mapping to Financial Statement line items. Reports mapped vs unmapped accounts and material value of unmapped accounts",
        inputFields: [],
        buttons: ["Auto-Map", "Scan Unmapped"],
        autoPulled: ["CoAAccount records with fsLineItem", "FSHeadWorkingPaper count"],
        outputs: ["Mapping percentage", "Mapped/unmapped account counts", "Unmapped material value", "Lead schedule count", "Top unmapped accounts"],
        commonErrors: ["BLOCKED when material accounts remain unmapped"],
      },
      {
        key: "planning-analytics",
        label: "Phase 5: Analytics, Materiality & Risk",
        purpose: "Monitors materiality set status (Draft/Approved), risk assessment count, and analytical procedures. Requires approved materiality and risks for APPROVED gate",
        inputFields: [],
        buttons: [],
        autoPulled: ["MaterialitySet records", "RiskAssessment count", "AnalyticalProcedure count"],
        outputs: ["Materiality status with OM/PM amounts", "Risk count", "Analytics count", "Planning score (0-100)"],
        commonErrors: ["Shows IN_PROGRESS when materiality exists but is not approved"],
      },
      {
        key: "sampling",
        label: "Phase 6: Population Build & Sampling",
        purpose: "Tracks population definitions and sample selections. Shows population count, value, sample sizes, and coverage percentage",
        inputFields: [],
        buttons: [],
        autoPulled: ["PopulationDefinition records", "Sample records"],
        outputs: ["Population count and total value", "Sample count and selected items", "Coverage percentage", "Approved samples count"],
        commonErrors: ["NOT_STARTED when populations have DRAFT status only"],
      },
      {
        key: "execution-wp",
        label: "Phase 7: Execution Workpapers",
        purpose: "Monitors FS Head working paper completion status and tracks unresolved misstatements",
        inputFields: [],
        buttons: [],
        autoPulled: ["FSHeadWorkingPaper records", "Misstatement records"],
        outputs: ["Completed/total workpapers", "In-progress workpapers", "Unresolved misstatements count and total amount"],
        commonErrors: ["Shows IN_PROGRESS when some workpapers are still in DRAFT"],
      },
      {
        key: "completion",
        label: "Phase 8: Completion & Reporting",
        purpose: "Checks readiness of final deliverables: audit report, management letter, completion memo, and finalization lock status",
        inputFields: [],
        buttons: [],
        autoPulled: ["AuditReport", "ManagementLetter", "CompletionMemo", "Engagement finalization status"],
        outputs: ["Report readiness percentage", "Component checklist", "Readiness blockers list", "Engagement status"],
        commonErrors: ["Blockers shown when completion memo is missing"],
      },
    ],
    workedExample: "Meridian Technologies FY2024 (ENG-2025-001): Staff uploads Meridian_Tech_FY2024_Workbook.xlsx containing TB (36 rows), GL (12,840 entries), and CoA (36 accounts). Phase 1 detects 3/5 sheets and marks PASSED. Phase 2 runs validation: all 4 checks PASS with DQ score 100/100. Phase 3 confirms TB-GL fully reconciled (difference: 0). Phase 4 shows 36/36 accounts mapped to FS hierarchy (100%). Phase 5: Materiality approved at OM PKR 12.75M / PM PKR 9.56M, 4 risks assessed, score 80. Phase 6: 4 populations built (1,736 items, PKR 1.19B value), 150 items sampled, all approved. Phase 7: 6/6 workpapers completed, 2 misstatements noted (1 adjusted, 1 unadjusted below PM). Phase 8: Audit report signed, management letter delivered, completion memo approved. Overall progress: 100%, zero blockers.",
  },
  {
    key: "portal-dashboard",
    label: "Client Portal Dashboard",
    routePath: "/portal/dashboard",
    phase: "Cross-Phase Tools",
    purpose: "Client-facing portal dashboard providing clients with visibility into their audit engagement status, outstanding requests, uploaded documents, and communication with the audit team.",
    prerequisites: ["Client portal access granted", "Active engagement"],
    isaReferences: ["ISA 230", "ISA 500"],
    roles: ["Client User"],
    approvals: [],
    locks: [],
    tabs: [
      { key: "overview", label: "Overview", purpose: "High-level view of engagement progress, key dates, and action items for the client", inputFields: [], buttons: ["View Engagement"], autoPulled: ["Engagement status", "Key milestones", "Outstanding request count"], outputs: ["Client engagement summary"], commonErrors: [] },
      { key: "documents", label: "Documents", purpose: "View and upload documents requested by the audit team", inputFields: ["File upload", "Document description"], buttons: ["Upload Document", "Download"], autoPulled: ["Document request list"], outputs: ["Uploaded document log"], commonErrors: ["Incorrect file format", "Uploading to wrong request"] },
      { key: "messages", label: "Messages", purpose: "Secure messaging between client and audit team", inputFields: ["Message text", "Attachments"], buttons: ["Send Message"], autoPulled: ["Message history"], outputs: ["Message thread"], commonErrors: [] },
    ],
    workedExample: "ABC & Co. CFO logs into the portal, sees 3 outstanding document requests (bank statements, vendor invoices, board minutes). Uploads bank statements and sends a message to the audit senior.",
  },
  {
    key: "portal-requests",
    label: "Client Portal Requests",
    routePath: "/portal/engagement/:id",
    phase: "Cross-Phase Tools",
    purpose: "Detailed view of all information and document requests from the audit team. Clients can view request details, upload responses, and track fulfillment status.",
    prerequisites: ["Client portal access granted", "Requests created by audit team"],
    isaReferences: ["ISA 500", "ISA 230"],
    roles: ["Client User"],
    approvals: [],
    locks: ["Requests locked after audit team marks as received"],
    tabs: [
      { key: "pending", label: "Pending", purpose: "List of outstanding requests awaiting client response", inputFields: ["Response upload", "Comments"], buttons: ["Upload Response", "Request Extension"], autoPulled: ["Request details", "Due dates", "Priority"], outputs: ["Submitted response record"], commonErrors: ["Missing required attachments", "Past-due requests"] },
      { key: "completed", label: "Completed", purpose: "Archive of fulfilled requests with response history", inputFields: [], buttons: ["Download Response"], autoPulled: ["Completed request history"], outputs: ["Request fulfillment log"], commonErrors: [] },
    ],
    workedExample: "ABC & Co. accountant sees 5 pending requests. Uploads bank confirmation response for Q4. Marks vendor reconciliation as complete. 2 requests still pending past due date, escalated to CFO.",
  },
];

export function getModuleByKey(key: string): GuideModule | undefined {
  return USER_GUIDE_REGISTRY.find(m => m.key === key);
}

export function getWorkspaceModules(): GuideModule[] {
  return USER_GUIDE_REGISTRY.filter(m => m.routePath.startsWith("/workspace/"));
}

export function getGlobalModules(): GuideModule[] {
  return USER_GUIDE_REGISTRY.filter(m => !m.routePath.startsWith("/workspace/"));
}
