import { FieldDataSource } from "@prisma/client";

export interface FieldBlueprintSeed {
  module: string;
  tab: string;
  fieldKey: string;
  label: string;
  description?: string;
  fieldType: string;
  required: boolean;
  requiredWhen?: Record<string, unknown>;
  dataSource: FieldDataSource;
  defaultValue?: unknown;
  validationRules?: Record<string, unknown>;
  roleLockRule?: string;
  minRoleToEdit?: string;
  standardsRef?: string;
  orderIndex: number;
}

export const fieldBlueprints: FieldBlueprintSeed[] = [
  // ===============================================
  // INFORMATION REQUISITION MODULE
  // ===============================================
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "bank_statements",
    label: "Bank Statements (All Accounts)",
    description: "Bank statements for all accounts for the audit period",
    fieldType: "evidence",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 500",
    orderIndex: 1,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "revenue_invoices_sample",
    label: "Revenue Invoices (Sample)",
    description: "Sample of sales invoices for testing",
    fieldType: "evidence",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 500",
    orderIndex: 2,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "payroll_records",
    label: "Payroll Records & Summaries",
    description: "Monthly payroll summaries and supporting records",
    fieldType: "evidence",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 500",
    orderIndex: 3,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "tax_returns_filings",
    label: "Tax Returns & Filings",
    description: "All tax returns and regulatory filings for the period",
    fieldType: "evidence",
    required: true,
    dataSource: "USER_INPUT",
    standardsRef: "ISA 250",
    orderIndex: 4,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "inventory_schedules",
    label: "Inventory Schedules & Count Sheets",
    description: "Year-end inventory schedules and physical count documentation",
    fieldType: "evidence",
    required: true,
    requiredWhen: { hasInventory: true },
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 501",
    orderIndex: 5,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "fixed_asset_register",
    label: "Fixed Asset Register",
    description: "Complete fixed asset register with additions and disposals",
    fieldType: "evidence",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 500",
    orderIndex: 6,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "bank_confirmation_letters",
    label: "Bank Confirmation Letters",
    description: "Signed bank confirmation letters for all accounts",
    fieldType: "evidence",
    required: true,
    dataSource: "USER_INPUT",
    standardsRef: "ISA 505",
    orderIndex: 7,
  },
  {
    module: "INFORMATION_REQUISITION",
    tab: "DOCUMENT_CHECKLIST",
    fieldKey: "legal_confirmations",
    label: "Legal Confirmations",
    description: "Lawyer confirmation letters regarding litigation",
    fieldType: "evidence",
    required: true,
    dataSource: "USER_INPUT",
    standardsRef: "ISA 501",
    orderIndex: 8,
  },

  // ===============================================
  // PRE-PLANNING MODULE
  // ===============================================
  {
    module: "PRE_PLANNING",
    tab: "ENGAGEMENT_BASICS",
    fieldKey: "reporting_currency",
    label: "Reporting Currency",
    description: "Primary currency used for financial reporting",
    fieldType: "select",
    required: true,
    dataSource: "TB_UPLOAD",
    defaultValue: "PKR",
    standardsRef: "ISA 210",
    orderIndex: 1,
  },
  {
    module: "PRE_PLANNING",
    tab: "ENGAGEMENT_BASICS",
    fieldKey: "period_end_date",
    label: "Period End Date",
    description: "Financial year end date",
    fieldType: "date",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 210",
    orderIndex: 2,
  },
  {
    module: "PRE_PLANNING",
    tab: "ENGAGEMENT_BASICS",
    fieldKey: "reporting_framework",
    label: "Applicable Reporting Framework",
    description: "Financial reporting standards (IFRS/IFRS for SMEs/Local GAAP)",
    fieldType: "select",
    required: true,
    dataSource: "USER_INPUT",
    defaultValue: "IFRS",
    standardsRef: "ISA 200",
    orderIndex: 3,
  },
  {
    module: "PRE_PLANNING",
    tab: "ENGAGEMENT_BASICS",
    fieldKey: "total_assets",
    label: "Total Assets",
    description: "Total assets from trial balance",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 4,
  },
  {
    module: "PRE_PLANNING",
    tab: "ENGAGEMENT_BASICS",
    fieldKey: "total_revenue",
    label: "Total Revenue",
    description: "Total revenue from trial balance",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 5,
  },
  {
    module: "PRE_PLANNING",
    tab: "ENGAGEMENT_BASICS",
    fieldKey: "total_equity",
    label: "Total Equity",
    description: "Total equity from trial balance",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 6,
  },

  // ===============================================
  // PLANNING MODULE - 14 TABS
  // ===============================================
  
  // TAB 1: FINANCIAL STATEMENTS
  {
    module: "PLANNING",
    tab: "FINANCIAL_STATEMENTS",
    fieldKey: "draft_bs_total_assets",
    label: "Draft BS - Total Assets",
    description: "Balance sheet total assets from TB mapping",
    fieldType: "currency",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 315",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "FINANCIAL_STATEMENTS",
    fieldKey: "draft_bs_total_liabilities",
    label: "Draft BS - Total Liabilities",
    description: "Balance sheet total liabilities from TB mapping",
    fieldType: "currency",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 315",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "FINANCIAL_STATEMENTS",
    fieldKey: "draft_bs_total_equity",
    label: "Draft BS - Total Equity",
    description: "Balance sheet total equity from TB mapping",
    fieldType: "currency",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 315",
    orderIndex: 3,
  },
  {
    module: "PLANNING",
    tab: "FINANCIAL_STATEMENTS",
    fieldKey: "draft_pl_total_revenue",
    label: "Draft PL - Total Revenue",
    description: "Income statement total revenue from TB mapping",
    fieldType: "currency",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 315",
    orderIndex: 4,
  },
  {
    module: "PLANNING",
    tab: "FINANCIAL_STATEMENTS",
    fieldKey: "draft_pl_net_profit",
    label: "Draft PL - Net Profit/Loss",
    description: "Net profit or loss from income statement",
    fieldType: "currency",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 315",
    orderIndex: 5,
  },
  {
    module: "PLANNING",
    tab: "FINANCIAL_STATEMENTS",
    fieldKey: "fs_heads_linked",
    label: "FS Heads Linked to TB",
    description: "Financial statement heads linked to trial balance accounts",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 315",
    orderIndex: 6,
  },

  // TAB 2: TEAM BRIEFING
  {
    module: "PLANNING",
    tab: "TEAM_BRIEFING",
    fieldKey: "transaction_volume",
    label: "Transaction Volume",
    description: "Total number of GL transactions in the period",
    fieldType: "number",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "TEAM_BRIEFING",
    fieldKey: "account_count",
    label: "Number of Accounts",
    description: "Total number of accounts in chart of accounts",
    fieldType: "number",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "TEAM_BRIEFING",
    fieldKey: "entity_size_classification",
    label: "Entity Size Classification",
    description: "Small/Medium/Large based on assets and revenue",
    fieldType: "select",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 3,
  },

  // TAB 3: ENTITY UNDERSTANDING
  {
    module: "PLANNING",
    tab: "ENTITY",
    fieldKey: "revenue_streams",
    label: "Revenue Streams Identified",
    description: "Revenue streams identified from GL analysis",
    fieldType: "json",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "ENTITY",
    fieldKey: "asset_composition",
    label: "Asset Composition",
    description: "Breakdown of asset categories from TB",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "ENTITY",
    fieldKey: "liability_composition",
    label: "Liability Composition",
    description: "Breakdown of liability categories from TB",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 3,
  },
  {
    module: "PLANNING",
    tab: "ENTITY",
    fieldKey: "gl_transaction_patterns",
    label: "GL Transaction Patterns",
    description: "Transaction patterns and anomalies from GL",
    fieldType: "json",
    required: false,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 4,
  },

  // TAB 4: RISK ASSESSMENT
  {
    module: "PLANNING",
    tab: "RISK",
    fieldKey: "significant_accounts",
    label: "Significant Accounts Identified",
    description: "Accounts identified as significant based on TB balances",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "RISK",
    fieldKey: "risk_candidates",
    label: "Risk Candidates from TB/GL",
    description: "Potential risk areas identified from data analysis",
    fieldType: "json",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 315",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "RISK",
    fieldKey: "fraud_risk_indicators",
    label: "Fraud Risk Indicators",
    description: "Fraud risk indicators from GL patterns",
    fieldType: "json",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 240",
    orderIndex: 3,
  },

  // TAB 5: ANALYTICAL PROCEDURES
  {
    module: "PLANNING",
    tab: "ANALYTICAL",
    fieldKey: "liquidity_ratios",
    label: "Liquidity Ratios",
    description: "Current ratio, quick ratio calculations",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 520",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "ANALYTICAL",
    fieldKey: "profitability_ratios",
    label: "Profitability Ratios",
    description: "Gross margin, net margin, ROA, ROE",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 520",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "ANALYTICAL",
    fieldKey: "trend_analysis",
    label: "Trend Analysis",
    description: "Year-over-year trend analysis",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 520",
    orderIndex: 3,
  },
  {
    module: "PLANNING",
    tab: "ANALYTICAL",
    fieldKey: "anomalies_detected",
    label: "Anomalies Detected",
    description: "Unusual fluctuations requiring investigation",
    fieldType: "json",
    required: false,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 520",
    orderIndex: 4,
  },

  // TAB 6: MATERIALITY
  {
    module: "PLANNING",
    tab: "MATERIALITY",
    fieldKey: "pbt_benchmark",
    label: "PBT Benchmark Value",
    description: "Profit before tax as materiality benchmark",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 320",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "MATERIALITY",
    fieldKey: "revenue_benchmark",
    label: "Revenue Benchmark Value",
    description: "Total revenue as materiality benchmark",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 320",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "MATERIALITY",
    fieldKey: "assets_benchmark",
    label: "Total Assets Benchmark Value",
    description: "Total assets as materiality benchmark",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 320",
    orderIndex: 3,
  },
  {
    module: "PLANNING",
    tab: "MATERIALITY",
    fieldKey: "equity_benchmark",
    label: "Equity Benchmark Value",
    description: "Total equity as materiality benchmark",
    fieldType: "currency",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 320",
    orderIndex: 4,
  },
  {
    module: "PLANNING",
    tab: "MATERIALITY",
    fieldKey: "suggested_materiality",
    label: "Suggested Overall Materiality",
    description: "AI-suggested overall materiality amount",
    fieldType: "currency",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 320",
    orderIndex: 5,
  },
  {
    module: "PLANNING",
    tab: "MATERIALITY",
    fieldKey: "performance_materiality",
    label: "Performance Materiality",
    description: "Performance materiality (typically 50-75% of overall)",
    fieldType: "currency",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 320",
    orderIndex: 6,
  },

  // TAB 7: WALKTHROUGHS
  {
    module: "PLANNING",
    tab: "WALKTHROUGHS",
    fieldKey: "cycles_from_gl",
    label: "Business Cycles from GL",
    description: "Transaction cycles identified from GL patterns",
    fieldType: "json",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "WALKTHROUGHS",
    fieldKey: "material_cycles",
    label: "Material Cycles for Walkthrough",
    description: "Cycles requiring walkthrough based on materiality",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 315",
    orderIndex: 2,
  },

  // TAB 8: GOING CONCERN
  {
    module: "PLANNING",
    tab: "GOING_CONCERN",
    fieldKey: "liquidity_flags",
    label: "Liquidity Warning Flags",
    description: "Liquidity concerns from TB analysis",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 570",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "GOING_CONCERN",
    fieldKey: "equity_flags",
    label: "Equity Warning Flags",
    description: "Equity deficiency concerns from TB",
    fieldType: "json",
    required: true,
    dataSource: "TB_UPLOAD",
    standardsRef: "ISA 570",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "GOING_CONCERN",
    fieldKey: "cash_stress_signals",
    label: "Cash Stress Signals",
    description: "Cash flow stress indicators from GL",
    fieldType: "json",
    required: false,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 570",
    orderIndex: 3,
  },

  // TAB 9: STRATEGY
  {
    module: "PLANNING",
    tab: "STRATEGY",
    fieldKey: "approach_per_fs_head",
    label: "Audit Approach per FS Head",
    description: "Suggested audit approach for each FS head",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 330",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "STRATEGY",
    fieldKey: "control_reliance_triggers",
    label: "Control Reliance Triggers",
    description: "Indicators for control reliance from GL",
    fieldType: "json",
    required: false,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 330",
    orderIndex: 2,
  },

  // TAB 10: SAMPLING
  {
    module: "PLANNING",
    tab: "SAMPLING",
    fieldKey: "sampling_frames",
    label: "Sampling Frames Available",
    description: "Population frames for sampling from GL",
    fieldType: "json",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 530",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "SAMPLING",
    fieldKey: "sampling_methods",
    label: "Sampling Methods Available",
    description: "Applicable sampling methods based on data",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 530",
    orderIndex: 2,
  },

  // TAB 11: AUDIT PROGRAM
  {
    module: "PLANNING",
    tab: "AUDIT_PROGRAM",
    fieldKey: "procedure_packs",
    label: "Procedure Packs per FS Head",
    description: "Standard procedure packs for each FS head",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 330",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "AUDIT_PROGRAM",
    fieldKey: "je_testing_required",
    label: "JE Testing Required",
    description: "Journal entry testing procedures if GL present",
    fieldType: "boolean",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 240",
    orderIndex: 2,
  },
  {
    module: "PLANNING",
    tab: "AUDIT_PROGRAM",
    fieldKey: "cutoff_tests_required",
    label: "Cutoff Tests Required",
    description: "Cutoff testing procedures if GL present",
    fieldType: "boolean",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 500",
    orderIndex: 3,
  },

  // TAB 12: QUALITY CONTROL
  {
    module: "PLANNING",
    tab: "QUALITY_CONTROL",
    fieldKey: "qc_triggers",
    label: "QC Triggers Identified",
    description: "Quality control triggers from engagement data",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISQM 1",
    orderIndex: 1,
  },
  {
    module: "PLANNING",
    tab: "QUALITY_CONTROL",
    fieldKey: "eqcr_required",
    label: "EQCR Required",
    description: "Whether engagement quality review is required",
    fieldType: "boolean",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISQM 1",
    orderIndex: 2,
  },

  // TAB 13: DOCUMENTATION & COMMUNICATION
  {
    module: "PLANNING",
    tab: "DOCUMENTATION",
    fieldKey: "planning_memo_sections",
    label: "Planning Memo Auto-Draft Sections",
    description: "Auto-generated planning memo sections",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 300",
    orderIndex: 1,
  },

  // TAB 14: SIGN-OFF
  {
    module: "PLANNING",
    tab: "SIGN_OFF",
    fieldKey: "gating_checklist_status",
    label: "Gating Checklist Status",
    description: "Status of all planning gate requirements",
    fieldType: "json",
    required: true,
    dataSource: "SYSTEM",
    standardsRef: "ISA 300",
    orderIndex: 1,
  },

  // ===============================================
  // EXECUTION MODULE
  // ===============================================
  {
    module: "EXECUTION",
    tab: "FS_HEAD_SECTIONS",
    fieldKey: "fs_heads_list",
    label: "FS Heads for Execution",
    description: "List of FS heads requiring execution procedures",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 330",
    orderIndex: 1,
  },
  {
    module: "EXECUTION",
    tab: "FS_HEAD_SECTIONS",
    fieldKey: "risks_per_fs_head",
    label: "Risks per FS Head",
    description: "Identified risks linked to each FS head",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 315",
    orderIndex: 2,
  },
  {
    module: "EXECUTION",
    tab: "FS_HEAD_SECTIONS",
    fieldKey: "assertions_per_fs_head",
    label: "Assertions per FS Head",
    description: "Relevant assertions for each FS head",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 315",
    orderIndex: 3,
  },
  {
    module: "EXECUTION",
    tab: "FS_HEAD_SECTIONS",
    fieldKey: "toc_tod_required",
    label: "TOC/TOD Requirements",
    description: "Tests of controls and details required per FS head",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 330",
    orderIndex: 4,
  },
  {
    module: "EXECUTION",
    tab: "FS_HEAD_SECTIONS",
    fieldKey: "evidence_placeholders",
    label: "Evidence Placeholders",
    description: "Evidence requirements per FS head",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 500",
    orderIndex: 5,
  },

  // ===============================================
  // FS HEADS MODULE
  // ===============================================
  {
    module: "FS_HEADS",
    tab: "DASHBOARD",
    fieldKey: "fs_heads_with_balances",
    label: "FS Heads with Lead Schedule Balances",
    description: "Complete list of FS heads with their balances",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 500",
    orderIndex: 1,
  },
  {
    module: "FS_HEADS",
    tab: "DASHBOARD",
    fieldKey: "population_statistics",
    label: "Population Statistics",
    description: "Population count and amount per FS head",
    fieldType: "json",
    required: true,
    dataSource: "GL_UPLOAD",
    standardsRef: "ISA 530",
    orderIndex: 2,
  },
  {
    module: "FS_HEADS",
    tab: "DASHBOARD",
    fieldKey: "sample_statistics",
    label: "Sample Statistics",
    description: "Sample count and amount per FS head",
    fieldType: "json",
    required: false,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 530",
    orderIndex: 3,
  },
  {
    module: "FS_HEADS",
    tab: "DASHBOARD",
    fieldKey: "coverage_percentage",
    label: "Coverage Percentage",
    description: "Audit coverage percentage per FS head",
    fieldType: "json",
    required: false,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 530",
    orderIndex: 4,
  },

  // ===============================================
  // FINALIZATION MODULE
  // ===============================================
  {
    module: "FINALIZATION",
    tab: "ADJUSTED_FS",
    fieldKey: "unadjusted_fs",
    label: "Unadjusted Financial Statements",
    description: "FS before audit adjustments",
    fieldType: "json",
    required: true,
    dataSource: "MAPPING",
    standardsRef: "ISA 450",
    orderIndex: 1,
  },
  {
    module: "FINALIZATION",
    tab: "ADJUSTED_FS",
    fieldKey: "audit_adjustments",
    label: "Audit Adjustments Summary",
    description: "Summary of all audit adjustments",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 450",
    orderIndex: 2,
  },
  {
    module: "FINALIZATION",
    tab: "ADJUSTED_FS",
    fieldKey: "adjusted_fs",
    label: "Adjusted Financial Statements",
    description: "FS after audit adjustments",
    fieldType: "json",
    required: true,
    dataSource: "PUSH_ROUTER",
    standardsRef: "ISA 450",
    orderIndex: 3,
  },
  {
    module: "FINALIZATION",
    tab: "COMPLETION_CHECKLIST",
    fieldKey: "completion_items",
    label: "Completion Checklist Items",
    description: "Required completion checklist items",
    fieldType: "json",
    required: true,
    dataSource: "SYSTEM",
    standardsRef: "ISA 220",
    orderIndex: 1,
  },
  {
    module: "FINALIZATION",
    tab: "SUBSEQUENT_EVENTS",
    fieldKey: "subsequent_events_review",
    label: "Subsequent Events Review",
    description: "Subsequent events review documentation",
    fieldType: "json",
    required: true,
    dataSource: "USER_INPUT",
    standardsRef: "ISA 560",
    orderIndex: 1,
  },
  {
    module: "FINALIZATION",
    tab: "GOING_CONCERN",
    fieldKey: "gc_conclusion",
    label: "Going Concern Conclusion",
    description: "Final going concern assessment",
    fieldType: "json",
    required: true,
    dataSource: "USER_INPUT",
    standardsRef: "ISA 570",
    orderIndex: 1,
  },
  {
    module: "FINALIZATION",
    tab: "REPORTING",
    fieldKey: "report_type",
    label: "Report Type",
    description: "Type of audit report to issue",
    fieldType: "select",
    required: true,
    dataSource: "USER_INPUT",
    standardsRef: "ISA 700",
    orderIndex: 1,
  },
  {
    module: "FINALIZATION",
    tab: "FINAL_NOTES",
    fieldKey: "final_notes",
    label: "Final Partner Notes",
    description: "Partner's final notes and observations",
    fieldType: "textarea",
    required: false,
    dataSource: "USER_INPUT",
    minRoleToEdit: "PARTNER",
    standardsRef: "ISA 220",
    orderIndex: 1,
  },

  // ===============================================
  // QUALITY REVIEW MODULE
  // ===============================================
  {
    module: "QUALITY_REVIEW",
    tab: "EQCR_CHECKLIST",
    fieldKey: "eqcr_checklist_items",
    label: "EQCR Checklist Items",
    description: "EQCR review checklist items",
    fieldType: "json",
    required: true,
    dataSource: "SYSTEM",
    minRoleToEdit: "EQCR",
    standardsRef: "ISQM 1",
    orderIndex: 1,
  },

  // ===============================================
  // INSPECTION MODULE
  // ===============================================
  {
    module: "INSPECTION",
    tab: "READINESS",
    fieldKey: "inspection_readiness",
    label: "Inspection Readiness Status",
    description: "Readiness for regulatory inspection",
    fieldType: "json",
    required: true,
    dataSource: "SYSTEM",
    standardsRef: "ISQM 1",
    orderIndex: 1,
  },
];
