import { prisma } from "../db";

const STANDARD_TEMPLATES = [
  {
    templateCode: "PRE-001",
    templateName: "Engagement Letter",
    templateCategory: "PRE_ENGAGEMENT",
    description: "Standard engagement letter confirming terms, scope, responsibilities, and fee arrangements",
    isaReferences: ["ISA 210", "ISQM 1"],
    applicablePhases: ["PRE_PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PRE-002",
    templateName: "Client Acceptance & Continuance Checklist",
    templateCategory: "PRE_ENGAGEMENT",
    description: "Risk assessment checklist for accepting or continuing an audit engagement",
    isaReferences: ["ISA 220", "ISQM 1"],
    applicablePhases: ["PRE_PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PRE-003",
    templateName: "Independence Declaration",
    templateCategory: "PRE_ENGAGEMENT",
    description: "Team member independence confirmation per IESBA Code of Ethics",
    isaReferences: ["ISA 220", "IESBA Code"],
    applicablePhases: ["PRE_PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PRE-004",
    templateName: "Anti-Money Laundering (AML) Checklist",
    templateCategory: "PRE_ENGAGEMENT",
    description: "Know Your Client (KYC) and AML compliance verification",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["PRE_PLANNING"],
    isRequired: false,
  },
  {
    templateCode: "REQ-001",
    templateName: "Information & Documents Requisition",
    templateCategory: "REQUISITION",
    description: "Comprehensive list of documents and information required from the client",
    isaReferences: ["ISA 230", "ISA 500"],
    applicablePhases: ["REQUISITION"],
    isRequired: true,
  },
  {
    templateCode: "REQ-002",
    templateName: "Client Confirmation Request - Banks",
    templateCategory: "REQUISITION",
    description: "Bank balance confirmation request letter format",
    isaReferences: ["ISA 505"],
    applicablePhases: ["REQUISITION"],
    isRequired: false,
  },
  {
    templateCode: "REQ-003",
    templateName: "Client Confirmation Request - Receivables",
    templateCategory: "REQUISITION",
    description: "Trade receivable balance confirmation request to debtors",
    isaReferences: ["ISA 505"],
    applicablePhases: ["REQUISITION"],
    isRequired: false,
  },
  {
    templateCode: "REQ-004",
    templateName: "Client Confirmation Request - Payables",
    templateCategory: "REQUISITION",
    description: "Trade payable balance confirmation request to creditors",
    isaReferences: ["ISA 505"],
    applicablePhases: ["REQUISITION"],
    isRequired: false,
  },
  {
    templateCode: "REQ-005",
    templateName: "Legal Advisor Confirmation",
    templateCategory: "REQUISITION",
    description: "Confirmation request to entity's legal counsel regarding litigation and claims",
    isaReferences: ["ISA 501"],
    applicablePhases: ["REQUISITION"],
    isRequired: false,
  },
  {
    templateCode: "REQ-006",
    templateName: "Tax Advisor Confirmation",
    templateCategory: "REQUISITION",
    description: "Confirmation request to entity's tax advisor regarding tax positions",
    isaReferences: ["ISA 501"],
    applicablePhases: ["REQUISITION"],
    isRequired: false,
  },
  {
    templateCode: "PLN-001",
    templateName: "Audit Planning Memorandum",
    templateCategory: "PLANNING",
    description: "Comprehensive planning document covering strategy, scope, materiality, risk assessment, and team allocation",
    isaReferences: ["ISA 300", "ISA 315"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-002",
    templateName: "Materiality Calculation Worksheet",
    templateCategory: "PLANNING",
    description: "Overall materiality, performance materiality, and trivial threshold calculations",
    isaReferences: ["ISA 320", "ISA 450"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-003",
    templateName: "Key Financial Ratios Analysis",
    templateCategory: "PLANNING",
    description: "Preliminary analytical procedures - financial ratio analysis and trend comparisons",
    isaReferences: ["ISA 315", "ISA 520"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-004",
    templateName: "Risk Assessment Matrix",
    templateCategory: "PLANNING",
    description: "Assessment of risks of material misstatement at financial statement and assertion levels",
    isaReferences: ["ISA 315", "ISA 330"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-005",
    templateName: "Fraud Risk Assessment",
    templateCategory: "PLANNING",
    description: "Assessment of fraud risk factors including management override, revenue recognition, and related parties",
    isaReferences: ["ISA 240", "ISA 550"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-006",
    templateName: "Audit Strategy & Approach",
    templateCategory: "PLANNING",
    description: "Overall audit strategy defining scope, timing, direction, and nature of procedures",
    isaReferences: ["ISA 300", "ISA 330"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-007",
    templateName: "Going Concern Assessment",
    templateCategory: "PLANNING",
    description: "Evaluation of entity's ability to continue as a going concern",
    isaReferences: ["ISA 570"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "PLN-008",
    templateName: "Related Party Identification",
    templateCategory: "PLANNING",
    description: "Identification and risk assessment of related party relationships and transactions",
    isaReferences: ["ISA 550"],
    applicablePhases: ["PLANNING"],
    isRequired: true,
  },
  {
    templateCode: "EXE-001",
    templateName: "Internal Controls Evaluation Checklist",
    templateCategory: "EXECUTION",
    description: "Evaluation of design and implementation of internal controls relevant to the audit",
    isaReferences: ["ISA 315", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: true,
  },
  {
    templateCode: "EXE-002",
    templateName: "Journal Entry Testing Program",
    templateCategory: "EXECUTION",
    description: "Testing of journal entries for indicators of management override of controls",
    isaReferences: ["ISA 240", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: true,
  },
  {
    templateCode: "EXE-003",
    templateName: "Substantive Analytical Procedures",
    templateCategory: "EXECUTION",
    description: "Template for performing substantive analytical procedures on financial data",
    isaReferences: ["ISA 520", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "EXE-004",
    templateName: "Audit Sampling Worksheet",
    templateCategory: "EXECUTION",
    description: "Sample selection, testing, and evaluation documentation",
    isaReferences: ["ISA 530"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "EXE-005",
    templateName: "Omitted Liabilities Testing",
    templateCategory: "EXECUTION",
    description: "Search for unrecorded liabilities at period end",
    isaReferences: ["ISA 500", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: true,
  },
  {
    templateCode: "WP-BS-001",
    templateName: "Property, Plant & Equipment Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of PPE additions, disposals, depreciation, and impairment",
    isaReferences: ["ISA 500", "IAS 16"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-002",
    templateName: "Intangible Assets Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of intangible assets, amortization, and impairment",
    isaReferences: ["ISA 500", "IAS 38"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-003",
    templateName: "Inventories Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Stock in trade verification including count attendance, valuation, and NRV testing",
    isaReferences: ["ISA 501", "IAS 2"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-004",
    templateName: "Trade Receivables Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Receivables testing including aging, confirmations, and ECL assessment",
    isaReferences: ["ISA 505", "IFRS 9"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-005",
    templateName: "Cash & Bank Balances Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Bank reconciliations, confirmation replies, and cash count verification",
    isaReferences: ["ISA 505", "ISA 500"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-006",
    templateName: "Long Term Investments Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of investment valuations, classifications, and impairment",
    isaReferences: ["ISA 500", "IFRS 9", "IAS 28"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-007",
    templateName: "Loans & Advances Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of short/long term loans, advances, and recoverability",
    isaReferences: ["ISA 500", "IFRS 9"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-008",
    templateName: "Share Capital & Reserves Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Verification of equity movements, dividends, and statutory reserves",
    isaReferences: ["ISA 500", "IAS 1"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-009",
    templateName: "Trade & Other Payables Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of creditor balances, confirmations, and completeness",
    isaReferences: ["ISA 505", "IAS 1"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-010",
    templateName: "Long Term Financing Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of loan agreements, covenants, interest calculations, and classifications",
    isaReferences: ["ISA 500", "IFRS 9", "IAS 1"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-011",
    templateName: "Staff Retirement Benefits Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Actuarial valuation review, plan assets, and disclosure verification",
    isaReferences: ["ISA 500", "IAS 19"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-012",
    templateName: "Deferred Taxation Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Deferred tax computation review and temporary difference analysis",
    isaReferences: ["ISA 500", "IAS 12"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-013",
    templateName: "Contingencies & Commitments Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Assessment and disclosure of contingent liabilities and capital commitments",
    isaReferences: ["ISA 501", "IAS 37"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-014",
    templateName: "Deposits & Prepayments Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of trade deposits, short-term prepayments, and recoverability",
    isaReferences: ["ISA 500"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-BS-015",
    templateName: "Tax Refunds Due Working Paper",
    templateCategory: "WORKING_PAPER_BS",
    description: "Testing of income tax, sales tax, and other tax refund balances",
    isaReferences: ["ISA 500", "IAS 12"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-001",
    templateName: "Revenue / Sales Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Revenue recognition testing, cut-off procedures, and disaggregation analysis",
    isaReferences: ["ISA 240", "ISA 330", "IFRS 15"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-002",
    templateName: "Cost of Sales Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Testing of cost of goods sold, input reconciliation, and margin analysis",
    isaReferences: ["ISA 500", "IAS 2"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-003",
    templateName: "Administrative Expenses Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Testing of administrative and general expenses against comparative periods",
    isaReferences: ["ISA 520", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-004",
    templateName: "Distribution Cost Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Testing of selling and distribution expenses",
    isaReferences: ["ISA 520", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-005",
    templateName: "Finance Cost Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Testing of interest expense, borrowing costs, and lease finance charges",
    isaReferences: ["ISA 500", "IFRS 9", "IFRS 16"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-006",
    templateName: "Other Income Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Testing of non-operating income, gains on disposal, and investment income",
    isaReferences: ["ISA 500", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-007",
    templateName: "Taxation Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Current tax computation, tax provision reconciliation, and return-to-provision analysis",
    isaReferences: ["ISA 500", "IAS 12"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "WP-PL-008",
    templateName: "Other Operating Expenses Working Paper",
    templateCategory: "WORKING_PAPER_PL",
    description: "Testing of other charges, impairments, and non-recurring items",
    isaReferences: ["ISA 500", "ISA 330"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "EXE-006",
    templateName: "Stock Take & Cash Count Program",
    templateCategory: "EXECUTION",
    description: "Physical inventory observation and cash count attendance program",
    isaReferences: ["ISA 501"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "EXE-007",
    templateName: "Minutes of Meeting Review",
    templateCategory: "EXECUTION",
    description: "Review of board/committee meeting minutes for audit-relevant matters",
    isaReferences: ["ISA 500", "ISA 315"],
    applicablePhases: ["EXECUTION"],
    isRequired: true,
  },
  {
    templateCode: "EXE-008",
    templateName: "Number of Employees Verification",
    templateCategory: "EXECUTION",
    description: "Verification of employee headcount for payroll and benefits testing",
    isaReferences: ["ISA 500"],
    applicablePhases: ["EXECUTION"],
    isRequired: false,
  },
  {
    templateCode: "FIN-001",
    templateName: "Management Representation Letter",
    templateCategory: "FINALIZATION",
    description: "Written representations from management confirming responsibility for financial statements",
    isaReferences: ["ISA 580"],
    applicablePhases: ["FINALIZATION"],
    isRequired: true,
  },
  {
    templateCode: "FIN-002",
    templateName: "Management Letter",
    templateCategory: "FINALIZATION",
    description: "Communication of internal control deficiencies and recommendations to management",
    isaReferences: ["ISA 265"],
    applicablePhases: ["FINALIZATION"],
    isRequired: true,
  },
  {
    templateCode: "FIN-003",
    templateName: "Summary of Audit Differences",
    templateCategory: "FINALIZATION",
    description: "Schedule of unadjusted audit differences and evaluation against materiality",
    isaReferences: ["ISA 450"],
    applicablePhases: ["FINALIZATION"],
    isRequired: true,
  },
  {
    templateCode: "FIN-004",
    templateName: "Subsequent Events Review",
    templateCategory: "FINALIZATION",
    description: "Evaluation of events occurring between period end and audit report date",
    isaReferences: ["ISA 560"],
    applicablePhases: ["FINALIZATION"],
    isRequired: true,
  },
  {
    templateCode: "FIN-005",
    templateName: "Audit Completion Memorandum",
    templateCategory: "FINALIZATION",
    description: "Final summary of audit findings, conclusions, and matters for partner attention",
    isaReferences: ["ISA 220", "ISA 230"],
    applicablePhases: ["FINALIZATION"],
    isRequired: true,
  },
  {
    templateCode: "FIN-006",
    templateName: "Going Concern Final Assessment",
    templateCategory: "FINALIZATION",
    description: "Final evaluation of going concern at completion stage",
    isaReferences: ["ISA 570"],
    applicablePhases: ["FINALIZATION"],
    isRequired: true,
  },
  {
    templateCode: "RPT-001",
    templateName: "Independent Auditor's Report",
    templateCategory: "REPORTING",
    description: "Standard unmodified/modified audit opinion report template",
    isaReferences: ["ISA 700", "ISA 705", "ISA 706"],
    applicablePhases: ["REPORTING"],
    isRequired: true,
  },
  {
    templateCode: "RPT-002",
    templateName: "Communication with TCWG",
    templateCategory: "REPORTING",
    description: "Communication of audit matters to Those Charged with Governance",
    isaReferences: ["ISA 260"],
    applicablePhases: ["REPORTING"],
    isRequired: true,
  },
  {
    templateCode: "RPT-003",
    templateName: "Key Audit Matters (KAM) Documentation",
    templateCategory: "REPORTING",
    description: "Determination and communication of Key Audit Matters for listed entities",
    isaReferences: ["ISA 701"],
    applicablePhases: ["REPORTING"],
    isRequired: false,
  },
  {
    templateCode: "QR-001",
    templateName: "Engagement Quality Review Checklist",
    templateCategory: "QUALITY_REVIEW",
    description: "EQCR reviewer's comprehensive checklist covering all significant judgments and conclusions",
    isaReferences: ["ISQM 2", "ISA 220"],
    applicablePhases: ["EQCR"],
    isRequired: true,
  },
  {
    templateCode: "QR-002",
    templateName: "Hot Review / Concurring Partner Review",
    templateCategory: "QUALITY_REVIEW",
    description: "Pre-issuance review checklist for high-risk engagements",
    isaReferences: ["ISQM 1", "ISQM 2"],
    applicablePhases: ["EQCR"],
    isRequired: false,
  },
  {
    templateCode: "ISQM-001",
    templateName: "Firm Quality Management Policies",
    templateCategory: "ISQM",
    description: "Firm-wide quality management system policies and procedures per ISQM 1",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: true,
  },
  {
    templateCode: "ISQM-002",
    templateName: "Annual Quality Survey Form",
    templateCategory: "ISQM",
    description: "Annual staff survey for quality culture assessment",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: false,
  },
  {
    templateCode: "ISQM-003",
    templateName: "Performance Feedback Form",
    templateCategory: "ISQM",
    description: "Team member performance evaluation form from leadership",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: false,
  },
  {
    templateCode: "ISQM-004",
    templateName: "Trainee Admission Form",
    templateCategory: "ISQM",
    description: "New trainee/article clerk admission and registration form",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: false,
  },
  {
    templateCode: "ISQM-005",
    templateName: "Candidate Evaluation Form",
    templateCategory: "ISQM",
    description: "Candidate screening and evaluation form for human resources",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: false,
  },
  {
    templateCode: "ISQM-006",
    templateName: "Appointment Letter Template",
    templateCategory: "ISQM",
    description: "Standard employee appointment/offer letter",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: false,
  },
  {
    templateCode: "ISQM-007",
    templateName: "Experience Letter Template",
    templateCategory: "ISQM",
    description: "Standard experience/service certificate letter",
    isaReferences: ["ISQM 1"],
    applicablePhases: ["INSPECTION"],
    isRequired: false,
  },
  {
    templateCode: "IDX-001",
    templateName: "Main Audit File Index",
    templateCategory: "DOCUMENTATION",
    description: "Master index for organizing the permanent and current audit file",
    isaReferences: ["ISA 230"],
    applicablePhases: ["PRE_PLANNING", "FINALIZATION"],
    isRequired: true,
  },
];

export async function seedTemplates() {
  const firm = await prisma.firm.findFirst();
  if (!firm) {
    console.log("No firm found, skipping template seeding");
    return;
  }

  let created = 0;
  let skipped = 0;

  for (const template of STANDARD_TEMPLATES) {
    const existing = await (prisma as any).documentTemplate?.findUnique({
      where: {
        firmId_templateCode: {
          firmId: firm.id,
          templateCode: template.templateCode,
        },
      },
    });

    if (existing) {
      skipped++;
      continue;
    }

    await (prisma as any).documentTemplate?.create({
      data: {
        firmId: firm.id,
        ...template,
        templateFormat: "HTML",
        isSystemTemplate: true,
        allowCustomization: true,
        isActive: true,
        version: 1,
      },
    });
    created++;
  }

  console.log(`Templates seeded: ${created} created, ${skipped} already existed (${STANDARD_TEMPLATES.length} total)`);
}
